### ISSUE TITLE
Error when use new version of plugin

### ISSUE THREAD

**Issue by lansz** [alibaba/terraform-provider#106]
```
➜ /Users/myvpc > terraform version
[WARN] /usr/local/Cellar/terraform/0.9.1_1/bin/terraform-provider-alicloud overrides an internal plugin for alicloud-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Terraform v0.9.2

➜ /Users/myvpc > terraform apply
[WARN] /usr/local/Cellar/terraform/0.9.1_1/bin/terraform-provider-alicloud overrides an internal plugin for alicloud-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Error asking for user input: 1 error(s) occurred:

* provider.alicloud: Incompatible API version with plugin. Plugin version: 2, Ours: 4
```

Any idea what cause this?

**Comment by demonwy** [comment]
@lansz 
What change have you make? I deduce that you have upgrade the Terraform?

It seems that alicloud-provider is integrated in terraform already, but in the path `/usr/local/Cellar/terraform/0.9.1_1/bin/` there is a `terraform-provider-alicloud` plugin mainwhile, cause the conflict.

Please safely delete `terraform-provider-alicloud` and try again.

Thanks

**Comment by lansz** [comment]
The problem is not conflict, it's about this message "provider.alicloud: Incompatible API version with plugin. Plugin version: 2, Ours: 4"

**Comment by shuwei-yin** [comment]
@lansz:
did you have both terraform binary file and terraform-provider-alicloud binary file in your PATH?

**Comment by demonwy** [comment]
@lansz 
please show me how to reproduce it.

Thanks

**Comment by demonwy** [comment]
@lansz 
I've reproduce your case, remove the `terraform-provider-alicloud ` problem fixed.

1. check terraform version
```
➜ bin terraform --version
[WARN] /usr/local/terraform/bin/terraform-provider-alicloud overrides an internal plugin for alicloud-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Terraform v0.9.2
```

2. put `terraform-provider-alicloud` in the bin path
```
➜  bin ls /usr/local/terraform/bin
terraform                   terraform-provider-alicloud

```
3. ran command `terraform plan` in your template folder
```
➜  alicloud-rds git:(master) ✗ terraform plan
[WARN] /usr/local/terraform/bin/terraform-provider-alicloud overrides an internal plugin for alicloud-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Error asking for user input: 1 error(s) occurred:

* provider.alicloud: Incompatible API version with plugin. Plugin version: 1, Ours: 4
```

4. remove `terraform-provider-alicloud` from bin path, and run `terraform plan` command again, then solved.
```
➜  alicloud-rds git:(master) ✗ terraform plan
provider.alicloud.access_key
  Access key of alicloud

  Enter a value: xxxx

provider.alicloud.secret_key
  Secret key of alicloud

  Enter a value: yyyy

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
```

Expect your replay.
Thanks

**Comment by lansz** [comment]
Yes, that's what I did.
But the thing is I'm trying to test the latest release of alicloud plugin here, download latest release and put it into /usr/local/terraform/bin is the only option since the builtin alicloud plugin comes with Terraform 0.9.2 is not have issue 98 (https://github.com/alibaba/terraform-provider/issues/98) fixed yet.

**Comment by shuwei-yin** [comment]
@lansz:

the bug fix haven't merge Terraform offical version, so you could use Terraform V0.8.0 addition terraform-alicloud-provider, cause the version 0.8.0 haven't include the alicloud provider so haven't conflict.

**Comment by shuwei-yin** [comment]
we will find better method to solving the conflict problem. thanks for your feedback :)

**Comment by lansz** [comment]
OK, thanks.

**Comment by demonwy** [comment]
@lansz 
The lastest version(0.9.2) of Terraform, has already fix the issue [#98](https://github.com/alibaba/terraform-provider/issues/98), please check the [test case](https://github.com/hashicorp/terraform/blob/master/builtin/providers/alicloud/resource_alicloud_security_group_rule_test.go#L188)

Thanks

**Comment by demonwy** [comment]
Except that, we have add new resource [alicloud_db_instance](https://www.terraform.io/docs/providers/alicloud/r/db_instance.html), please try on if you needed it.

Thanks

**Comment by lansz** [comment]
@demonwy I tried again, and you are right, #98 is fixed in the latest version.

**Comment by demonwy** [comment]
Thanks for your replay.
