### ISSUE TITLE
alicloud_nat_gateway port forwarding

### ISSUE THREAD

**Issue by benjaminchodroff** [alibaba/terraform-provider#109]
Does terraform support alicloud_nat_gateway with port forwarding definition? I tried searching the documentation but it appears this may be an enhancement request? 

Something like this would be very helpful:
resource "alicloud_nat_gateway_port_forwarding" "edge-all-forward" {
  external_eip_id = ...
  internal_ip or instance_id (required) = ...
  exteranal_ports = -1/-1
  internal_ports = -1/-1
  protocal_type = tcp/udp/any
}

**Comment by shuwei-yin** [comment]
@benjaminchodroff 
the forwarding resource is "alicloud_forward_entry", the example you could take look https://github.com/alibaba/terraform-provider/blob/dev/terraform/examples/alicloud-vpc-snat/main.tf

But the "SNAT" and "forward" can't support except China users.
you could refrence https://github.com/alibaba/terraform-provider/blob/dev/terraform/examples/alicloud-vpc-route-entry/main.tf to achieve the SNAT.

**Comment by benjaminchodroff** [comment]
Perfect! I missed this because the terraform aliyun documentation does not include alicloud_forward_entry:
https://www.terraform.io/docs/providers/alicloud/

My apologies. This is great! 👍
