### ISSUE TITLE
allocate_public_ip false not obeyed

### ISSUE THREAD

**Issue by benjaminchodroff** [alibaba/terraform-provider#110]
If you set allocate_public_ip = false and accidentally set internet_max_bandwidth_in or internet_max_bandwidth_out to any value, the instance will be assigned a public ip address. The expected behavior would be to obey allocate_public_ip and ignore the internet_max_bandwidth_* directives.

**Comment by xiaozhu36** [comment]
Hello benjaminchodroff,

Could you please show me your example? According your description I have made a test just now, and didn't meet with problem what you said.

Thanks,
He Guimin

**Comment by shuwei-yin** [comment]
@benjaminchodroff 
you are right. the allocate_public_ip = false had a bug in earlier version, now it's fixed, but have not merge the Terraform official version, you could download the alicloud last version to verify it.
you have to set allocate_public_ip = false and internet_max_bandwidth_out=0, then the ECS will not allocate ip, if internet_max_bandwidth_out is not equal zero, just allocate_public_ip = false it's not effect.

**Comment by benjaminchodroff** [comment]
Thank you! 👍
