### ISSUE TITLE
Setting internet_charge_type on VPC instance forces new resource every apply

### ISSUE THREAD

**Issue by benjaminchodroff** [alibaba/terraform-provider#111]
If you accidentally set internet_charge_type to either PayByBandwidth or PayByTraffic when allocate_public_ip=false (VPC), the resource will get forced to recreate every time terraform apply is called.

The expected behavior is to ignore internet_charge_type when allocate_public_ip=false.

**Comment by xiaozhu36** [comment]
Hello benjaminchodroff,

At present, alicloud ECS doesn't support modification the value of internet_charge_type for one existed instance, and so do alicloud/terraform-provider. The internet_charge_type will be invalid when allocate_public_ip=false, but internet_charge_type doesn't depend on allocate_public_ip. So, if you don't want to allocate public ip for one instance, you can remove internet_charge_type or don't modify it.


Thanks,
He Guimin

**Comment by benjaminchodroff** [comment]
I have worked around this issue but it may catch others by surprise. I would expect at the very least that if you set "allocate_public_ip=false" and set either internet_charge_type, internet_max_bandwidth_in, or internet_max_bandwidth_out that the alicloud provider should present the user an error due to the contradiction. Otherwise, a user may accidentally get an instance on the public internet when they did not intend to have one. 

This current model presents a challenge when creating instances that must either be public or private. Because terraform does not support conditional logic, it would be ideal if you could control public/private by just setting "allocate_public_ip" and ignore the other settings if present. Just my opinion :)

**Comment by xiaozhu36** [comment]
Hello @benjaminchodroff ,

Thank you for your suggest. You are right and we have considered the problem when we dev and test,  but we haven't found the ideal other solution for the present. There are many similar issue, and we will keep on working for solving it.

Thanks,
Guimin He

**Comment by benjaminchodroff** [comment]
Agree, "Working as designed." My work around is to assume the user correctly sets only appropriate variables IF the instance is public vs private. Thanks for the help.
