### ISSUE TITLE
chaging imgage_id can not work

### ISSUE THREAD

**Issue by foxracle** [alibaba/terraform-provider#114]
after changing the image_id and security_groups attribute in alicloud_instance block,  here is the logs of terraform plan and terraform apply.

logs of terraform plan:

===========================

~ alicloud_instance.example
    image_id:                   "xxxx" => "yyyy"
    security_groups.3716797384: "" => "sg-yyyy"
    security_groups.3812892935: "sg-xxxx" => ""

=============================

logs of terraform apply:

===========================
alicloud_instance.example: Refreshing state... (ID: i-bp1hgp7jllqsxxbylsgs)
alicloud_instance.example: Modifying... (ID: i-bp1hgp7jllqsxxbylsgs)
  image_id:                   "xxxx" => "yyyy"
  security_groups.3716797384: "" => "yyyy"
  security_groups.3812892935: "sg-xxxx" => ""
alicloud_instance.example: Still modifying... (ID: i-bp1hgp7jllqsxxbylsgs, 10s elapsed)
alicloud_instance.example: Still modifying... (ID: i-bp1hgp7jllqsxxbylsgs, 20s elapsed)
alicloud_instance.example: Still modifying... (ID: i-bp1hgp7jllqsxxbylsgs, 30s elapsed)
alicloud_instance.example: Still modifying... (ID: i-bp1hgp7jllqsxxbylsgs, 40s elapsed)
alicloud_instance.example: Modifications complete (ID: i-bp1hgp7jllqsxxbylsgs)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

=============================

from the logs above, the changes should be applied, but what we confirmed on the ecs console page is diffenrent: the security group has been changed but not the image_id.

by the way, with the command terraform show we can also confirmed that the image_id not be changed.

**Comment by xiaozhu36** [comment]
Hello @foxracle 

Alicloud doesn't support changing image_id, and changing image_id means it will create a new resource. The issue is ours reckless and we should set image_id's attribution as 'ForceNew' .

Thank you for your contribution.

Thanks,
Guimin

**Comment by foxracle** [comment]
@xiaozhu36  

Thanks for you reply.

>Alicloud doesn't support changing image_id

you mean not yet supported now but it is on the way, OR  it should not be supported in alicloud, even in the future?
creating a new resource is not a kind of action under IaC?

**Comment by yswwei** [comment]
we will supported it in the future, now not yet supported :)

**Comment by shuwei-yin** [comment]
@foxracle 
we will supported it in the future, now not yet supported :)

**Comment by xiaozhu36** [comment]
Hello @foxracle 

Now, alicloud has supported changing image_id in the version 1.0.6, and it can reset system disk size when changing image_id. Terraform official hasn't integrated it, but you can download it from https://github.com/alibaba/terraform-provider/releases/tag/V1.0.6 . 

Thanks,
Guimin
