### ISSUE TITLE
Can we have `users` directive just like AWS provider

### ISSUE THREAD

**Issue by elaijuh** [alibaba/terraform-provider#125]
I think it's a common use case to create an instance with users pre-created as well, so that we can just ssh to without setting the password

**Comment by demonwy** [comment]
Hi @elaijuh,
I'am not quite catch your point. Is the `users` your mentioned means key-pair?

About ssh to ecs without password, you can walk through by `user_data`, If needed we can provide a sample. By the way, alicloud_provider will support key-pair in the near future.



Regards,
YueWang

**Comment by elaijuh** [comment]
that'll be awesome if you can share an example with `user_data`

**Comment by demonwy** [comment]
@elaijuh  thanks for your suggestion.
If it is key-pair, we will  support recently, it's on our schedule list already.



Regards
YueWang

**Comment by xiaozhu36** [comment]
Hi @elaijuh 

Terraform-Provider-Alicloud has supported 'Key Pair' resource and it can help you to login ECS instances using SSH Key more conveniently. Welcome to download and use it from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.5, thanks.

Regards,
Guimin He
