### ISSUE TITLE
How long update

### ISSUE THREAD

**Issue by wow3065** [alibaba/terraform-provider#129]
Can you tell me the frequency of the project update, will also increase the support of other Ali cloud resources?

Thank you.

**Comment by demonwy** [comment]
Hi @wow3065 ,
Thanks for your question.

We have Full-time colleagues in charge for the alicloud provider now.
Mainly we support a resource take about 2~3 weeks, including code, ut, samples and docs.
The issues and bugs, we should reply and fix as soon as possible.

Recently, we have support RDS, ESS and OSS already, and next will be DOCKER container.
Looking forward to your suggestion.

Regards,
YueWang

**Comment by wow3065** [comment]
Thank you very much
