### ISSUE TITLE
I just change zone from beijing to shanghai in alicloud-ecs-vpc, but it doesn't work

### ISSUE THREAD

**Issue by opsforce** [alibaba/terraform-provider#131]
opsforce-Mac:alicloud-ecs-vpc opsforce$ terraform apply
var.ecs_type
  Enter a value: ecs.n1.tiny

alicloud_disk.disk: Creating...
  availability_zone: "" => "cn-shanghai-a"
  category:          "" => "cloud_ssd"
  size:              "" => "40"
  status:            "" => "<computed>"
alicloud_instance.instance: Creating...
  allocate_public_ip:         "" => "false"
  availability_zone:          "" => "cn-shanghai-a"
  host_name:                  "" => "mfg-cloud-01"
  image_id:                   "" => "m-uf64gabqbdpj51otskfc"
  instance_charge_type:       "" => "PostPaid"
  instance_name:              "" => "mfg-cloud-01"
  instance_type:              "" => "ecs.n1.tiny"
  internet_charge_type:       "" => "PayByTraffic"
  internet_max_bandwidth_out: "" => "1"
  io_optimized:               "" => "optimized"
  password:                   "<sensitive>" => "<sensitive>"
  private_ip:                 "" => "<computed>"
  public_ip:                  "" => "<computed>"
  security_groups.#:          "" => "1"
  security_groups.3433535800: "" => "sg-uf63o7ulmhwcxq3d22yc"
  status:                     "" => "<computed>"
  subnet_id:                  "" => "<computed>"
  system_disk_category:       "" => "cloud_efficiency"
  system_disk_size:           "" => "<computed>"
  tags.%:                     "" => "2"
  tags.dc:                    "" => "shanghai"
  tags.role:                  "" => "cloud"
  vswitch_id:                 "" => "vsw-uf6ikmcb6dxiepi9t0b2h"
Error applying plan:

2 error(s) occurred:

* alicloud_disk.disk: 1 error(s) occurred:

* alicloud_disk.disk: availability_zone not exists in range cn-beijing, all zones are [cn-beijing-d cn-beijing-a cn-beijing-b cn-beijing-c]
* alicloud_instance.instance: 1 error(s) occurred:

* alicloud_instance.instance: availability_zone not exists in range cn-beijing, all zones are [cn-beijing-d cn-beijing-a cn-beijing-b cn-beijing-c]

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by xiaozhu36** [comment]
Hello @opsforce 

I'm very glad about that you use ours terraform-provider to apply ecs and other products. 

Alibaba/terraform-provider will provide one default region 'cn-beijing' when the parameter 'region' isn't be specified in the main.tf. So, if you want to change available-zone, you must set appropriate region. You can avoid above issue via adding the following code to the main.tf:

provider "alicloud" {
  region = "cn-shanghai"
}

Regards,
Guimin

**Comment by opsforce** [comment]
Hi @xiaozhu36 

ok, got it, I'll test it, thanks

**Comment by opsforce** [comment]
Hi @xiaozhu36 

I found some tags issues, but I update terraform version to 0.9.5, it's ok now, Thx

and I test it, I found it public ip also allocate when I change default variable of allocate_public_ip to 'false'.

variable "allocate_public_ip" {
  default = false
}

Regards,
ming jao

**Comment by opsforce** [comment]
oOO, I find it  in #110
