### ISSUE TITLE
About userdata function in official terraform

### ISSUE THREAD

**Issue by mosuke5** [alibaba/terraform-provider#143]
Hi
Do you have a plan to post PR about adding ECS's userdata to official terraform?
I want to use userdata!!

**Comment by shuwei-yin** [comment]
the userdata is supported of offical terraform, the docs is missed :)

**Comment by shuwei-yin** [comment]
please reference the code: https://github.com/hashicorp/terraform/blob/master/builtin/providers/alicloud/resource_alicloud_instance.go

**Comment by shuwei-yin** [comment]
and I saw the "terraform-for-alicloud-examples" in your repo, It's very nice, you can send mail to us  if you have any problem, the email address is "guimin.hgm@alibaba-inc.com" or "demon.wy@alibaba-inc.com" or "shuwei.yin@alibaba-inc.com"

**Comment by mosuke5** [comment]
sorry. i checked PR but overlooked.
im looking forward to marging it.

thank you for seeing my repo!
by the way, do you have a mailing list, slack channel or dingtalk group about this repository?

**Comment by mosuke5** [comment]
sorry official already have supported userdata.
ok!!

**Comment by mosuke5** [comment]
Sorry for reopening.
I will post PR to update official documents to add `user_data`.
Is following update right? I think it's ok.

```
## Argument Reference
...
* `user_data` - (Optional) The user data to provide when launching the instance.
```

**Comment by xiaozhu36** [comment]
Great, I think it's ok and thank you for your contribution.

**Comment by mosuke5** [comment]
ok!!
