### ISSUE TITLE
Error thrown when creating multiple VSwitch(s) at the same time

### ISSUE THREAD

**Issue by telescreen** [alibaba/terraform-provider#144]
```
# VPCの作成
resource "alicloud_vpc" "vpc" {
  name = "mongovpc"
  cidr_block = "10.0.0.0/16"
}

# vswitchの作成。mongo-primary
resource "alicloud_vswitch" "mongo-primary" {
  name              = "mongo-primary"
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.0.0/19"
  availability_zone = "${var.zone}"
}

# vswitchの作成。mongo-secondary0
resource "alicloud_vswitch" "mongo-secondary0" {
  name              = "mongo-secondary0"
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.32.0/19"
  availability_zone = "${var.zone}"
}
```

When trying to create multiple vswitchs, I get the following message. I think it should be no problem writing tf file like this.

```
* alicloud_vswitch.mongo-primary: Create subnet got a error :Aliyun API Error: RequestId: 89BA91FE-886A-49AD-B43F-2FA32604DA49 Status Code: 400 Code: IncorrectVSwitchStatus Message: VSwitch Creation simultaneously is not supported.
* alicloud_vswitch.nat-bastion: 1 error(s) occurred:

* alicloud_vswitch.nat-bastion: Create subnet got a error :Aliyun API Error: RequestId: 6CAF7C47-267F-46F3-8C8B-6007E768E758 Status Code: 400 Code: IncorrectVSwitchStatus Message: VSwitch Creation simultaneously is not supported.
```

**Comment by demonwy** [comment]
Hi @telescreen 
Thanks for your report.
As the error info above, the create vswitch API does not support concurrent. We will handle it with retry in our provider tomorrow.

You can run the command `terraform apply` twice for workaround before we fix it.

Regards
YueWang

**Comment by telescreen** [comment]
Thank you! Looking forward to the update version of aliyun provider.

**Comment by xiaozhu36** [comment]
Hi @telescreen 

Thank you for your contribution. The latest package has beeb published, and it fixed above problem. You can download and update it from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.0 . Thanks.

Regards,
Guimin He

**Comment by telescreen** [comment]
Thank you. Let me try to rebuild my alicloud provider and check it.
