### ISSUE TITLE
Support for Container Service

### ISSUE THREAD

**Issue by benjamin-bergia** [alibaba/terraform-provider#146]
Is there any plan to support container service resources to this provider ?

The creation of clusters involves multiple moving parts and being able to quickly provision a new cluster with vpc, nat, etc,  would be really convenient.

**Comment by xiaozhu36** [comment]
Hi @benjamin-bergia 

Thank you for your attention. As you expected, we have considered to support container service resource. Now we are developing it and we will strive for publishing it as soon as possible. Please keep patience for it, thanks.

Regards,
Guimin He

**Comment by benjamin-bergia** [comment]
Great, thanks.

No need to keep this issue open then.
