### ISSUE TITLE
Error when trying to create RDS

### ISSUE THREAD

**Issue by telescreen** [alibaba/terraform-provider#147]
I have a RDS definition as below

```
# RDSの作成
resource "alicloud_db_instance" "db" {
    engine = "MySQL"
    engine_version = "5.6"
    vswitch_id = "${alicloud_vswitch.vsw.id}"
    security_ips = ["${alicloud_instance.web.private_ip}"]
    db_instance_class = "rds.mysql.t1.small"
    db_instance_storage = "10"
    db_instance_net_type = "Intranet"
}
```

When trying to apply this definition, I got following error messages

** 1st time terraform apply **

```
1 error(s) occurred:

* alicloud_db_instance.db: 1 error(s) occurred:

* alicloud_db_instance.db: WaitForInstance Running got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"D5D34CFD-9707-4469-8DB1-C78DD2F72CD3"}, HostId:"rds.ap-northeast-1.aliyuncs.com", Code:"Forbidden.InstanceNotFound", Message:"The specified instance is not found."}, StatusCode:404}
```

** 2nd time terraform apply **

```
1 error(s) occurred:

* alicloud_db_instance.db: 1 error(s) occurred:

* alicloud_db_instance.db: Error modify security ips 192.168.2.81: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"0F86BD27-49FF-49F6-BA63-1DA71FC3C0B2"}, HostId:"rds.ap-northeast-1.aliyuncs.com", Code:"OperationDenied.DBInstanceStatus", Message:"The operation is not permitted due to status of instance."}, StatusCode:403}
```

I think the provider should wait until the instance is fully initialized

**Comment by demonwy** [comment]
@telescreen 
Thanks for your report. 
I am checking it, and will reply you as soon as i got the answer.

**Comment by demonwy** [comment]
Hi @telescreen 
I have checked our code and logic, is as expected.
Please use our lasted plugin https://github.com/alibaba/terraform-provider/releases/tag/V1.1.0 and try again.


Thanks 
YueWang

**Comment by telescreen** [comment]
The issue happened with default provider of terraform (0.9.6).
I tried to overwrite the default provider by your V1.1.0 tag, but it threw another error message. Did I do something wrong?

```
Error running plan: 1 error(s) occurred:

* provider.alicloud: Cannot find endpoint in the region: "ap-northeast-1"
```

**Comment by shuwei-yin** [comment]
@telescreen  thank you for your report, this is issue, we will fixed it, and before you could change another region. sorry for that.

**Comment by demonwy** [comment]
@telescreen 
I've checked our plugin, there are some limits to ap-northeast-1 region.
I've fix the logic and update the alicloud plugin binary at https://github.com/alibaba/terraform-provider/releases/tag/V1.1.1.

Please download and try again. Sorry the troubles bring to you.

Thanks
YueWang

**Comment by telescreen** [comment]
Thank you. I downloaded V1.1.1 and it worked
