### ISSUE TITLE
Can't create databases in RDS

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#148]
In .tf file, I used:
```
  master_user_name = "${var.db_user_name}"
  master_user_password = "${var.db_password}"
  preferred_backup_time = "${var.preferred_backup_time}"
  db_mappings = [
    {
      db_name = "dscp"
      character_set_name = "utf8mb4"
    },
    {
      db_name = "try_dscp"
      character_set_name = "utf8mb4"
    }
  ]
```

The user has been created successfully, but Terraform failed to create the databases specified.
The error response is:

> Error applying plan:
>
> 1 error(s) occurred:
> 
> * alicloud_db_instance.rds: 1 error(s) occurred:
> 
> * alicloud_db_instance.rds: Failure create database try_dscp:  &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"B5E194AC-B38E-4134-838B-A449DA64519A"}, HostId:"rds.aliyuncs.com", Code:"OperationDenied.DBInstanceStatus", Message:"The operation is not permitted due to status of instance."}, StatusCode:403}

Seems the creation failed because the status of RDS was "creating",
how to fix this issue ?

**Comment by demonwy** [comment]
@RainFlying thanks for your report.
please give me some time to test it.
I'll reply you as soon as possible.

Thanks

**Comment by demonwy** [comment]
Hi @RainFlying ,
I've check the logic and run a test case which is like yours, it is OK in my environment.
What is the version of your terraform?

Could you please download lasted alicloud plugin version by the link https://github.com/alibaba/terraform-provider/releases/tag/V1.1.1 , and try again?
Any problem please let me know.

Regards,
YueWang

**Comment by RainFlying** [comment]
rainflying@rainflying-mac ~ % terraform --version
Terraform v0.9.6

rainflying@rainflying-mac ~ % cat ~/.terraformrc
providers {
  ansible = "/usr/local/bin/terraform-provisioner-ansible"
  alicloud = "/usr/local/bin/terraform-provider-alicloud"
}

terraform-providier-alicloud is downloaded from the URL you mentioned.

**Comment by RainFlying** [comment]
By the way, Terraform is managed by [asdf](https://github.com/asdf-vm/asdf).

**Comment by demonwy** [comment]
@RainFlying  With terraform-provider version V1.1.1 is not work for you?
please show me more info, that i can find the point for you.

Thanks

**Comment by RainFlying** [comment]
Didn't work with version 1.1.1 of provider.
I was using this version since the beginning.
What else info do you need ?
The whole tf file ?

**Comment by RainFlying** [comment]
@demonwy Just realize there is a newer version. I'll try this version later this week.

**Comment by demonwy** [comment]
@RainFlying  OK. Expect your good news.

**Comment by RainFlying** [comment]
Worked after upgraded to version 1.1.1.
