### ISSUE TITLE
Can we add additional white ip list to security_ips of existing RDS not managed by terraform

### ISSUE THREAD

**Issue by foxracle** [alibaba/terraform-provider#152]
Can we add additional white ip list to security_ips of existing RDS not managed by terraform？

**Comment by demonwy** [comment]
@foxracle 
Certainly, you can assign security_ips with any ip address. 

ps: [rds plugin docs link](https://www.terraform.io/docs/providers/alicloud/r/db_instance.html#security_ips)

Thanks
YueWang

**Comment by foxracle** [comment]
@demonwy 
even the RDS is not managed by terraform? I could not find somethings like security_group_rule in alicoud provider module. Could you tell me the details?

**Comment by demonwy** [comment]
@foxracle 
Sorry i've misunderstand your question.
The RDS must be created by terraform, which you can assign security_ips to.
