### ISSUE TITLE
everytime change security_ips of rds

### ISSUE THREAD

**Issue by mosuke5** [alibaba/terraform-provider#156]
Hi. I created 2 ecs instances and rds and add those instances to security_ips.
Everytime I execute `terraform plan`, following changes is shown.
Please check it.

```
~ alicloud_db_instance.rds
    security_ips.0: "192.168.1.179" => "192.168.1.181"
    security_ips.1: "192.168.1.181" => "192.168.1.179"
```

**Comment by xiaozhu36** [comment]
Hi @mosuke5

Thank you for your feedback, and I have found the reason that system would sort security ips after adding them successfully. So if inputting them orderly, you would avoid above defect.

However, it doesn't affect the final result, and we will also improve it as soon as possible, thanks.

Regards,
Guimin

**Comment by xiaozhu36** [comment]
Hi @mosuke5 

I have improved above defect and you can download and update your package from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.2 , thanks.

Regards,
Guimin He
