### ISSUE TITLE
Not able to import existing resource

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#158]
```
 % terraform import alicloud_db_instance.test 'rm-j6cymcqykvo948205'
alicloud_db_instance.test: Importing from ID "rm-j6cymcqykvo948205"...
Error importing: 1 error(s) occurred:

* alicloud_db_instance.test (import id: rm-j6cymcqykvo948205): import alicloud_db_instance.test (id: rm-j6cymcqykvo948205): resource alicloud_db_instance doesn't support import
```

Will "import" be supported in the future version of alicloud provider ?

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

Thank you for your feedback. At present, we haven't support 'import' function and it will be published in the near future. Can I have a idea that your application scenarios and the importance of it for you? Thanks.

Regards,
Guimin

**Comment by RainFlying** [comment]
Hi,
Currently we have more than 80 ECS instances and more than 35 RDS instances. Those instances are created before I switched to Terraform. We need to import those instances to Terraform first in order to manage them with Terraform.

**Comment by xiaozhu36** [comment]
Hi @RainFlying

Thank you for your feedback. I'm very appreciate your idea and using Terraform can conveniently manage your infrastructure. According to your idea, believing there are many users also have same idea, and we will support it as soon as possible. Please be patient, thanks.


Regards,
Guimin

**Comment by xiaozhu36** [comment]
Hi @RainFlying

In order to support 'import', can I have a idea how do you use 'import' to manage infrastructure?  As far as I known, 'import' function can put infrastructure information to tf.state not template, and without template how to update them? Thanks.

Regards,
Guimin

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

I have released the 'import' function and you can download and update your package from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.3 , thanks.

Regards,
Guimin He
