### ISSUE TITLE
Unable to create cloud disk

### ISSUE THREAD

**Issue by telescreen** [alibaba/terraform-provider#182]
Hi, I have a terraform script to create cloud disk. When the script is run, I got following errors

```
* alicloud_disk.disks.0: CreateDisk got a error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"960D174D-69D8-4085-9190-3F4F4E1DDC95"}, HostId:"ecs.ap-northeast-1.aliyuncs.com", Code:"Forbidden.RAM", Message:"User not authorized to operate on the specified resource, or this API doesn't support RAM."}, StatusCode:403}
```

I used to run this script without errors. My account is RAM account with Administrator privilegess.

**Comment by xiaozhu36** [comment]
Hi @telescreen 

Thank you for your feedback. At present, we only support 'cloud_ssd' and 'cloud_efficiency' disk. Please update it and try again.

By the way, which version is your terraform-provider-alicloud? If it >= v1.1.2, you would get warning message before you create disk, thanks.

Regards,
Guimin

**Comment by telescreen** [comment]
No, I'm using "cloud_efficiency" so it is not my problem here.
My error is the API is telling me it doesn't support RAM account to create disk (which happen recently). I used to be able to run this terraform script without problems.

I'm running newest terraform-provider (v1.1.5)

**Comment by xiaozhu36** [comment]
Hi @telescreen 

Thank you for your feedabck. I have a mistaken understand. The error is related to RAM account, but I haven't found the reason. Just now, I used a ram account to create a disk in the ap-northeast-1a successfully. So I want you to ensure two things:
1. Could you please ensure above error still exists by trying again?
2. Could you please ensure above error also happens in the console? (https://ecs.console.aliyun.com/#/create/clouddisk/?data=eyJkYXRhIjp7InZtX3JlZ2lvbl9ubyI6ImFwLXNvdXRoZWFzdC1vczMwLWEwMSJ9fQ%3D%3D)

Thanks.
Guimin

**Comment by xiaozhu36** [comment]
Hi @telescreen 

Just now, I retrieved your privileges and it shows you have not administrator privilege. Maybe your privilege has been modified. Please confirm it and try again, thanks.

Regards,
Guimin

**Comment by telescreen** [comment]
Hi, 
Apologize for reporting a wrong bug. 
I discovered that the error is due to me using a wrong access key / secret. I re-issued a new key and had no problems now. 

Thank you for your support!
