### ISSUE TITLE
Failed to create db instance

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#185]
When creating db instance, I got the following error:

Error applying plan:

1 error(s) occurred:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: WaitForInstance Running got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"9815849C-D79F-4ACC-9376-9C2235EDABAE"}, HostId:"rds.aliyuncs.com", Code:"InvalidDBInstanceId.NotFound", Message:"DBInstanceIdentifier does not refer to an existing DB instance."}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

The tf file:
resource "alicloud_db_instance" "rds" {
  engine = "${var.engine}"
  engine_version = "${var.engine_version}"
  db_instance_class = "${var.db_instance_class}"
  db_instance_storage = "${var.db_instance_storage}"
  instance_charge_type = "${var.db_instance_charge_type}"
  period = "${var.period}"
  #zone_id = "${var.zone_id}"
  allocate_public_connection = true
  db_instance_net_type = "${var.db_instance_net_type}"
  instance_network_type = "${var.instance_network_type}"
  vswitch_id = "${var.vswitch_id}"
  master_user_name = "${var.db_user_name}"
  master_user_password = "${var.db_password}"
  preferred_backup_time = "${var.preferred_backup_time}"
  preferred_backup_period = "${var.preferred_backup_period}"
  backup_retention_period = "${var.backup_retention_period}"
  db_mappings = [
    {
      db_name = "dscp"
      character_set_name = "utf8mb4"
    },
    {
      db_name = "try_dscp"
      character_set_name = "utf8mb4"
    }
  ]
  security_ips = ["${alicloud_instance.web1.private_ip}", "${alicloud_instance.web2.private_ip}", "202.131.80.74", "202.131.84.134", "211.24.114.202"]

  provisioner local-exec {
    command = "echo ${self.connections} >> rds_connections.txt"
  }
}

The instance was created partially successfully. The instance was created but the user and database were not created.

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

Thank you for your report and I'm sorry for that you have happened above it. 

I have fixed above bug and you can download and update your package from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.7 , thanks.

Regards,
Guimin He

**Comment by RainFlying** [comment]
Hi, the previous issue was fixed. However I encountered a new issue. It might be network issue. But the RDS instance was created partially. Please have a look at the following error message:

Error applying plan:

1 error(s) occurred:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: Create db account dscp error: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://rds.aliyuncs.com?AccessKeyId=LTAIqJ1Hi37g1Ki7&A
ccountName=dscp&AccountPassword=WZWfq4NlHQuw3QM4l2Qv7ENd9zA%3D&Action=CreateAccount&DBInstanceId=rm-j6cg039yi6hezrp9z&Format=JSON&SignatureMethod=HMAC-SHA1&SignatureNonce=_90H4U5Hh9l0cHDRM5QEZtxPs4mX4
06j&SignatureVersion=1.0&Timestamp=2017-08-26T10%3A30%3A29Z&Version=2014-08-15&Signature=f2EaOIu%2B71R6WQ%2BQZ34VblFVqMI%3D: net/http: TLS handshake timeout

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

I'm sorry for that you have happened above it.
This is a timeout error when creating account, and maybe it results from we set a short waiting time. We will make a test and fix the issue, thanks.


Regards,
Guimin He

**Comment by RainFlying** [comment]
Hi, found another issue.

Error applying plan:

1 error(s) occurred:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: Create db account dscp error: Aliyun API Error: RequestId: 79A16FD1-1889-44D2-8FC0-E51E0A8D166D Status Code: 400 Code: InvalidAccountPassword.Malformed Message: The specified $
arameter "AccountPassword" is not valid.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


However, I haven't specified any "AccountPassword" in the terraform config file.

  master_user_password = "${var.db_password}"

**Comment by RainFlying** [comment]
This issue appears again. Please have a check.
I'm running terraform v0.10.8 with alicloud provider version 1.2.10

Error: Error applying plan:

2 error(s) occurred:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: Create db account dscp error: Aliyun API Error: RequestId: C01A2917-31FA-448B-98FD-B7562BABBFDA Status Code: 400 Code: InvalidAccountPassword.Malformed Message: The specified parameter "AccountPassword" is not valid.
* alicloud_slb_attachment.frontend-pub: 1 error(s) occurred:

* alicloud_slb_attachment.frontend-pub: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://slb-pop.aliyuncs.com?AccessKeyId=LTAIqJ1Hi37g1Ki7&Action=AddBackendServers&BackendServers=%5B%7B%22ServerId%22%3A%22i-j6c9i06m840gcjemiggw%22%2C%22Weight%22%3A100%7D%2C%7B%22ServerId%22%3A%22i-j6cfq59pve68nqsgbns5%22%2C%22Weight%22%3A100%7D%5D&Format=JSON&LoadBalancerId=lb-j6cwlzsbbqlmvwocrq3uo&SignatureMethod=HMAC-SHA1&SignatureNonce=HoA2lB2qYlxNWJ__sTVQIzblXGoFVMC5&SignatureVersion=1.0&Timestamp=2017-11-17T07%3A49%3A57Z&Version=2014-05-15&Signature=4sGloqkA%2Blg1RrhJeLThkGpZ370%3D: EOF

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

I am sorry for that. We knew the issue and we are working for it. Please resolve it by retrying, thanks.

**Comment by RainFlying** [comment]
Updated to version 1.5.0, found other errors:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: Error creating Alicloud db instance: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"DF02B56A-00DD-4BB2-BFE9-6137B47B0040"}, HostId:"rds.aliyuncs.com", Code:"InternalError", Message:"The request processing has failed due to some unknown error, exception or failure."}, StatusCode:500}

**Comment by xiaozhu36** [comment]
Hi @RainFlying I am sorry for that. The issue has been fixed by version [1.5.2](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.2), and please be update. Thanks a lot.

Regards
He Guimin

**Comment by RainFlying** [comment]
Hi, @xiaozhu36 . The issue has been fixed, db instances was created successfully.
However, there appears to be another small issue.
I used "alicloud_db_connection" to allocate Internet connection string for db instane. Howver, no public connection was available after run terraform apply. Check the following config:

resource "alicloud_db_connection" "default" {
  instance_id = "${alicloud_db_instance.rds.id}"
}

According to the docs, only instance_id is required for the allocation of Internet connection string.

**Comment by xiaozhu36** [comment]
Hi @RainFlying Is there the error detail? And please login in Web console to ensure it no public connection string. Thanks a lot.

**Comment by RainFlying** [comment]
Tried another time, got the following error message:

1 error(s) occurred:

* alicloud_db_connection.default: 1 error(s) occurred:

* alicloud_db_connection.default: AllocateInstancePublicConnection got an error: &errors.errorString{s:"Allocate db connection got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:\"1D7000D5-9B48-4595-B6AB-0DEFBE27038C\"}, HostId:\"rds.aliyuncs.com\", Code:\"OperationDenied\", Message:\"The requested resource is sold out in the specified zone; try other types of resources or other regions and zones.\"}, StatusCode:403}."}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by RainFlying** [comment]
But I can allocate Internet connection string in the web console.

**Comment by xiaozhu36** [comment]
Hi @RainFlying It may be a RDS bug. Could you delete the public connection by web console and then terraform apply again?

**Comment by RainFlying** [comment]
Public connection was not created. I didn't create ti manually. I tried 'terraform apply' twice.

**Comment by xiaozhu36** [comment]
Hi @RainFlying The issue result from the RDS instance has already existed a same connection with you are going to allocate and there is a connection conflict. The issue I will fix in the next version. At present, setting a specified 'connection_prefix'  can avoid the conflict. Please try again, thanks a lot.


Regards,
He Guimin

**Comment by RainFlying** [comment]
Thanks, @xiaozhu36 , I get your point now.
Variable 'connection_prefix' defaults to the instance id, which has been already used by the private connection string. According to the rule of public connection string, I thought it should be instance_id + letter 'o'. In the next version, will the public connection string default to instance_id + letter 'o'?

**Comment by xiaozhu36** [comment]
Hi @RainFlying You are great! I am confirming with RDS team. If the API without default value, to be consistent with Web Console, I will make it default to instance_id + '0o'.

**Comment by xiaozhu36** [comment]
Hi @RainFlying About 'connection_prefix' has been fixed by version [1.6.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.6.0), and please update. Thanks a lot.
