### ISSUE TITLE
User data in ess scaling configuration 

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#186]
It would be nice to have user_data in alicloud_ess_scaling_configuration,  and also for root disk size.

Thanks

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your suggestion. It has been in ours schedule and we will support it as soon as possible.

Regards,
Guimin

**Comment by xiaozhu36** [comment]
@bittopaz Please refer to #229 , thanks a lot.
