### ISSUE TITLE
Difference between this repo and "terraform-providers/terraform-provider-alicloud"

### ISSUE THREAD

**Issue by Z10N0110** [alibaba/terraform-provider#188]
Hello, could anyone tell me what's the difference between this repo and https://github.com/terraform-providers/terraform-provider-alicloud ?

**Comment by xiaozhu36** [comment]
Hi @Z10N0110 

Welcome to use and experience terraform-provider-alicloud. This repo is maintained by ourselves and it contains the latest provider function. The repo https://github.com/terraform-providers/terraform-provider-alicloud is maintained by Terraform Official but its function is developed by our team. When the PRs we pulled  are merged and the new version is released by Terraform Official, you can use its latest function. 

I suggest you to download and use the latest package from https://github.com/alibaba/terraform-provider/releases, thanks.

Regards,
Guimin

**Comment by Z10N0110** [comment]
Thanks for the quick response.
I'll take the advice.
