### ISSUE TITLE
Docs for the new resources

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#194]
I am so excited to see this project is actively developed.

But now I can only check [here](https://www.terraform.io/docs/providers/alicloud/index.html) for docs, 
is there any place I can check and see the docs for the new resources.

Thanks
Xiaoyu

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your feedback. We will provide a good solution as soon as possible, and now you can get provider information from https://github.com/alibaba/terraform-provider-docs, thanks.

Regards,
Guimin

**Comment by bittopaz** [comment]
K, thanks @xiaozhu36
