### ISSUE TITLE
OSS as a terraform backend

### ISSUE THREAD

**Issue by benjamin-bergia** [alibaba/terraform-provider#195]
For users in mainland China, having OSS as a terraform backend would be very nice. I don't know if locking would be possible on OSS but it would be a real plus.

**Comment by xiaozhu36** [comment]
Hi @benjamin-bergia 

Thank you for your feedback. Just as you said, OSS can be a nice backend for terraform, and we have noticed it. The solution we will consider to support in the near future, thanks.

Regards,
Guimin

**Comment by jhagege** [comment]
Hi, would love to see OSS as a terraform backend. 
Are you still considering implementing it ? 
Thanks !

**Comment by veysiertekin** [comment]
@xiaozhu36 S3 is supported  as a backend but not OSS. Is there any plan?
