### ISSUE TITLE
Missing examples of attaching RAM role to an ecs instance

### ISSUE THREAD

**Issue by ayung1-docker** [alibaba/terraform-provider#202]
In /terraform/examples/alicloud-ram/main.tf, can you provide an example on how to attach a RAM role to an ECS instance using Terraform? The equivalent API call would be:
https://www.alibabacloud.com/help/doc-detail/54244.htm?spm=a3c0i.o54235en.a3.2.42f2a33fM0yxT6

**Comment by bittopaz** [comment]
I guess it is not supported yet

**Comment by xiaozhu36** [comment]
Hi @ayung1-docker 

Thank you for your suggestion. We are going to provide this function in this week. Please be patient, thanks.

Regards,
Guimin

**Comment by bittopaz** [comment]
👍 @xiaozhu36

**Comment by xiaozhu36** [comment]
Hi @ayung1-docker @bittopaz 

We have released the new package and it can support attaching RAM role to one or more ecs instances. You can download and update your package from https://github.com/alibaba/terraform-provider/releases/tag/V1.1.9 , thanks.

Regards,
Guimin

**Comment by ayung1-docker** [comment]
Thanks @xiaozhu36. Closing this issue.
