### ISSUE TITLE
负载均衡器一更新就报错

### ISSUE THREAD

**Issue by fsword** [alibaba/terraform-provider#218]
每次更新负载均衡器的时候就报如下错误，但实际上这个 LoadBalanceId并没有错误，更不是找不到，我怀疑这个和删除SLB需要手机短信验证有关。

```
Error applying plan:

2 error(s) occurred:

* alicloud_slb_attachment.default: 1 error(s) occurred:

* alicloud_slb_attachment.default: Aliyun API Error: RequestId: D078414B-5528-4D7F-A35C-0EB5AF1B7411 Status Code: 404 Code: InvalidLoadBalancerId.NotFound Message: LoadBalancerId does not exist.
* null_resource.docker_rancher: 1 error(s) occurred:

* Script exited with non-zero exit status: 127
```

**Comment by xiaozhu36** [comment]
@fsword 您好，这个应该不是SLB找不到的原因，可能是您的SLB的实例的网络类型跟所要添加的ECS实例的网络类型不匹配的原因，请先确定下SLB和ECS的网络类型，然后再遵循如下的添加规则进行尝试：
1. 经典网络的公网负载均衡实例，可添加经典网络类型的ECS或者同属于同一VPC的ECS；
2. 专有网络的私网负载均衡实例，仅能添加和负载均衡实例相同VPC内的ECS；
3. 经典网络的私网负载均衡实例，仅能添加经典网络类型的ECS。

谢谢
何贵民

**Comment by fsword** [comment]
应该不是这个原因，我之前设置了vpc id，vswitch id，然后改个小地方就要重新recreate resource，然后就报错了

**Comment by xiaozhu36** [comment]
您好，那可能得看具体情况了，我帮您问问SLB团队的开发人员，请他们帮忙解决下，谢谢。

**Comment by xiaozhu36** [comment]
您好，请问这个问题现在解决了么？如果没解决您尝试下载最新的provider [v1.3.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.3.0). 谢谢
