### ISSUE TITLE
ecs instance user data是不是后台运行了？

### ISSUE THREAD

**Issue by fsword** [alibaba/terraform-provider#223]
tf脚本如下——
```
resource "alicloud_instance" "nodes" {
  count = "${var.node_num}"
  vswitch_id = "${alicloud_vswitch.vswitch.id}"
  image_id = "${var.ethereum_instance_image_id == "" ? data.alicloud_images.default.images.0.id : var.ethereum_instance_image_id }"
  availability_zone = "${var.availability_zone}"
  instance_type = "ecs.n4.large"
  security_groups = ["${var.common_sg_id}"]
  user_data = "curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh"

  internet_charge_type = "PayByTraffic"
  internet_max_bandwidth_out = 10

  allocate_public_ip = true
  key_name = "deploy"

  instance_name = "${format("%s-%02d", "eth-node", count.index+1)}"
  instance_charge_type = "PostPaid"
  system_disk_category = "cloud_efficiency"
  system_disk_size = "40"
}
```
执行 terraform apply ，很快就成功结束，然后直接登录宿主机，发现docker的安装进程还在运行

**Comment by xiaozhu36** [comment]
您好，terraform的执行是不会区判断userdata里程序的运行程序的，只要是ecs启动成功，并且ecs的状态变为running，它的执行就是结束，谢谢。

**Comment by fsword** [comment]
这样会导致后续任务被干扰的，而且这会导致user data失去了意义，我们将不得不把所有东西都用null_resource来包装

**Comment by demonwy** [comment]
Terraform更关注于IaaS层的资源编排，应用的编排推荐用Ansible.

**Comment by fsword** [comment]
这样解释是不够的，我们期望的是在terraform脚本中安装docker并启动rancher agent，然后应用编排就可以交给rancher了，而现有的方式满足不了

**Comment by zhuzhih2017** [comment]
@fsword 能否使用packer制作包含docker的镜像，然后使用terraform来创建资源？这样应该能够避免你遇到的问题。

**Comment by muyufan** [comment]
terraform不是有provisioners的功能吗？
https://www.terraform.io/docs/provisioners/remote-exec.html

**Comment by xiaozhu36** [comment]
正如上文所说的，推荐使用https://www.terraform.io/docs/provisioners/remote-exec.html。目前terraform无法做到等待user-data执行完了才告知instance创建完成。Terraform是资源编排工具，当资源准备好了，也就是处于running状态时，terraform就认为这个资源已经创建完成，至于instance里面的用户进程，terraform无法获取状态，同时目前userdata也未能提供对应的解决方案。

这个issue我将关闭，如果您还有问题，请重新打开。
