### ISSUE TITLE
Questions about Alicloud dns record permission

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#226]
As far as I know, Alicloud DNS is now using 万网, and the DNS console page can only be accessed by ROOT account.

Questions:

1. Can I use my RAM account to do DNS management with the Alicloud provider?

2. I bought my DNS from Godday, but DNS server is pointing to Alicloud DNS, and managed from the DNS console, is it possible to use terraform code to manage them?

Thanks
Xiaoyu

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

1. RAM account can do DNS management if only it has DNS management privilege, whatever DNS console or Alicloud provider.
2. At present, Alicloud provider has support to manage DNS record and set group for DNS.
Thanks.

Regards,
He Guimin

**Comment by bittopaz** [comment]
@xiaozhu36 thanks for the reply.

Accord to the [doc](https://help.aliyun.com/knowledge_detail/39742.html), I could not find anything about DNS management, it is so confusing..

**Comment by xiaozhu36** [comment]
@bittopaz 

I'm sorry for that. Just now, I have consulted DNS developers and got a unfortunate result that at present RAM account can not support to manage DNS, but I have mentioned this demand for them. Please be patient, thanks.

Regards,
He Guimin
