### ISSUE TITLE
Support SLB rules

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#231]
SLB supports forwarding rules as described here: https://help.aliyun.com/document_detail/35226.html?spm=5176.doc35226.6.671.625Omh

Also the go sdk used in this provider also support the rule in SLB: https://github.com/denverdino/aliyungo/blob/master/slb/rules.go

Do you have a plan to support this, please?

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your suggestion. The function we plan to support and could you please provide your demand or application scenario to help us make it better, thanks.

Regards,
He Guimin

**Comment by bittopaz** [comment]
We have about 30~50 services with the domain *.example.com, such as: a.example.com, b.example.com, etc.

We share all these services with one SLB, and create a few virtual server groups in the SLB, and then use the forwarding rules to forward requests based on the DNS name.

Currently we doing the configuration from web console, which is tiring...

**Comment by xiaozhu36** [comment]
Hi @bittopaz Provider version [1.6.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.6.0) has supported slb_rule. Please update. Thanks a lot.

Regards
He Guimin
