### ISSUE TITLE
The specified parameter "HostName" is not valid

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#242]
I am trying to set the hostname of ECS with latest alicloud provider, but I got the error as below:

```sh
* alicloud_instance.eslaccess.4: Modify instance attribute got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"05D68CD0-2767-41A6-A01F-F5BD48B93E94"}, HostId:"ecs-cn-hangzhou.aliyuncs.com", Code:"InvalidHostName.Malformed", Message:"The specified parameter \"HostName\" is not valid."}, StatusCode:400}
* module.eslaccess.alicloud_instance.eslaccess[3]: 1 error(s) occurred:
```

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Above error results from you inputed a invalid hostname. Our hostname has following constraints:

1. It cannot start or end with a dot(.) or a hyphen (-) and it cannot have two or more consecutive dots (.) or hyphens (-); Cannot contain only digits.
2. Can contain uppercase or lowercase letters, digits, dots (.), and hyphens (-)
3. On Windows, the host name can be up to 15 characters in length and on other OSs, such as Linux, the host name can be up to 30 characters in length.

Please according above constraints and try again, thanks a lot.

Regards,
He Guimin

**Comment by bittopaz** [comment]
` it cannot have two or more consecutive dots (.) or hyphens (-)`.

Oh, I see. 

Thanks @xiaozhu36
