### ISSUE TITLE
nas目前还不能支持

### ISSUE THREAD

**Issue by fsword** [alibaba/terraform-provider#243]
目前对文件系统存储的支持主要还是disk，这个不能支持在线扩容，需要加入对nas的支持

**Comment by xiaozhu36** [comment]
@fsword 您好，

我们目前还未支持nas，您方便介绍您的具体需求么？以便帮助我们更好的去设计和实现nas的resource，非常感谢。

祝好
何贵民

**Comment by fsword** [comment]
需要支持nas的最主要原因是disk不能在线扩容，我本来期望能够用nas管理存储，这样随着业务增长，不用重新分配磁盘空间，现在的workaround方案是将disk做成lvm，这个依赖很多手工操作，对terraofrm来说不友好

**Comment by xiaozhu36** [comment]
@fsword 您好，

非常感谢您的反馈，后续我们会对nas予以支持，烦请耐心等待，谢谢

祝好
何贵民
