### ISSUE TITLE
阿里云市场中的编排类商品是否支持Terraform发布？

### ISSUE THREAD

**Issue by baotingfang** [alibaba/terraform-provider#245]
阿里云市场中的编排类商品是否支持Terraform发布？ 如果支持的话，是否有参考的文档或示例？

**Comment by xiaozhu36** [comment]
@baotingfang  您好，

非常感谢您的提问，目前terraform provider alicloud主要以支持云产品为主，暂时没有云市场商品方面的需求。您方便提供下您的具体使用需求或者应用场景么？我们将在综合考虑后给您满意的答复，非常感谢。

祝好
何贵民

**Comment by baotingfang** [comment]
@xiaozhu36 非常感谢你的回复。

我们期望在阿里的云市场上发布我们的产品， 目前看来只有“编排类”商品符合我们的要求。 和阿里的技术人员沟通后， 需要使用阿里提供的ROS工具进行资源编排。 事实上， 我们有很多在terraform上的使用经验， 并且terraform也是使用广泛的跨云平台的编排工具， 另外，阿里云上某些很常用的功能没有，比如terraform在批量创建机器时，支持自动获取实例索引；并行创建资源效率也比较高。因此期望能通过terraform技术，发布我们的产品。
