### ISSUE TITLE
Add more nexthop_type  to alicloud_route_entry 

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#250]
I'm trying to setup the route entry after I created alicloud_router_interface between my two vpcs.

So I'm have configure as below:

```
resource "alicloud_route_entry" "aux_to_beta" {
  route_table_id        = "${module.vpc.route_table_id}"
  destination_cidrblock = "172.19.0.0/16"
  nexthop_type          = "RouterInterface"
  nexthop_id            = "${alicloud_router_interface.aux_to_beta_peering.id}"
}
```

But after executed, I got the result: `alicloud_route_entry.aux_to_beta: nexthop_type must be one of Instance Tunnel`

Can we add more nexthop_type? According to [Doc](https://help.aliyun.com/document_detail/36012.html?spm=5176.product27706.6.644.xgEChw), `Instance|Tunnel|HaVip|RouterInterface|VpnGateway` are supported.

And the RouterInterface is quite useful.

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your suggestion. We will support more nexthop_type, please be patient, thanks a lot.

Regards,
He Guimin

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Route entry nexthop type 'RouterInterface' has been supported in the [terraform-provider](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.6), please download and update it, thanks.

Regards,
He Guimin

**Comment by bittopaz** [comment]
Thanks @xiaozhu36
