### ISSUE TITLE
instance_name默认为ECS-Instance导致kubernetes安装失败

### ISSUE THREAD

**Issue by ofsole** [alibaba/terraform-provider#262]
如果新建立的ECS的实例名称和实例id不一致，安装kubernetes指定cloud provider为alicloud会导致如下报错
 kubelet_node_status.go:73] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: instance not found
具体使用的脚本为 https://yq.aliyun.com/articles/73922 上提供的，如果手动创建ECS就没问题。

**Comment by xiaozhu36** [comment]
@ofsole 您好

非常抱歉让您遇到了这个问题，请问现在恢复了么？如果没有恢复方便提供下更多的错误信息么？您反映的这个问题我也是第一次遇到，一般情况下是不会出现问题的。谢谢

祝好
何贵民

**Comment by ofsole** [comment]
@xiaozhu36 您好
  现在还没恢复，现在通过阿里云创建kubernetes cluster只能通过ROS和手动新建ECS机器后用https://yq.aliyun.com/articles/73922或者https://yq.aliyun.com/articles/68921提供的安装方法安装，没办法用terraform plan，terraform apply 直接一键创建ECS并初始化kubernete。
具体详细信息请见如下Gist
https://gist.github.com/ofsole/9a6a7d7bdfee3386ee7c4020a099f38e
可能主要在于terraform provision ECS的时候修改了实例名称。
有点类似截图其他用户碰到的问题。
![issue](https://user-images.githubusercontent.com/3815749/32428030-b2097178-c2fe-11e7-8c83-6912d140fa0b.png)

**Comment by xiaozhu36** [comment]
@ofsole 您好，terraform provider不会对用户传入的实例name进行变更和改动，这个问题应该是kubernetes的cloud provider的问题，已经反馈给相关同学予以解决， 谢谢！

**Comment by spacexnice** [comment]
您好， 阿里云CloudProvider默认需要您配置kuberenetes各个组件的--hostname-override 为${region}.${instance-id}   ，这是为了规避用户可能会改实例名称及hostname的问题，同时提供跨region的兼容性所做的一个改变。   目前只支持VPC环境。region和instance-id可以通过
```
    region=$(curl --retry 5  -sSL http://100.100.100.200/latest/meta-data/region-id)
    insid=$(curl --retry 5  -sSL http://100.100.100.200/latest/meta-data/instance-id)
    if [ "" == "$region" -o "" == "$insid" ];then
        kube::common::log "can not get regionid and instanceid! \
            curl --retry 5 -sSL http://100.100.100.200/latest/meta-data/region-id" && exit 256
    fi
    export NODE_ID=$region.$insid
```
获得

**Comment by ofsole** [comment]
@spacexnice 您好，明白了，谢谢，问题已经解决。
