### ISSUE TITLE
Failed to create RDS instances

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#264]
Sometimes it works, sometimes it failed.
The error message:
1 error(s) occurred:

* alicloud_db_instance.rds: 1 error(s) occurred:

* alicloud_db_instance.rds: Failure create database try_dscp: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"6D531939-87C5-49DE-AB73-4F56644DC507"}, HostId:"rds.a
liyuncs.com", Code:"OperationDenied.DBInstanceStatus", Message:"The current status of the specified instance does not support this operation."}, StatusCode:403}

I think it's not related to permissions. Because the RDS was created, and the whitelist IPs were added successfully. The user was also created, but not the databases.

I'm using Terraform v0.9.10 with provider v1.2.6.

**Comment by xiaozhu36** [comment]
Hi @RainFlying 

I am sorry for that. I have fix the bug in the [v1.2.8](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.8). Please download and update it.
