### ISSUE TITLE
Looks like something broken on master branch

### ISSUE THREAD

**Issue by nobjohns** [alibaba/terraform-provider#269]
```
$ go get ./...
# github.com/alibaba/terraform-provider/alicloud
alicloud/resource_alicloud_ess_scalinggroup.go:123:16: cannot use d.Get("min_size").(int) (type int) as type *int in assignment
alicloud/resource_alicloud_ess_scalinggroup.go:128:16: cannot use d.Get("max_size").(int) (type int) as type *int in assignment
```

**Comment by xiaozhu36** [comment]
Hi @nobjohns 

It looks like type of 'min_size' and 'max_size' have been updated. You can modify its type to int in the file vendor/github.com/denverdino/aliyungo/ess/group.go temporarily, and I also to update it, thanks.

Regards
He Guimin

**Comment by nobjohns** [comment]
Thanks @xiaozhu36 
Just created a PR to fix this and similar issues in the future
https://github.com/alibaba/terraform-provider/pull/272

**Comment by xiaozhu36** [comment]
Hi @nobjohns 

The issue result from Go SDK changing field 'MinSize' and 'MaxSize'. Now, it has been fixed, and please download and try again, thanks a lot
