### ISSUE TITLE
SLB health_check_interval cannot be higher than 5

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#273]
I'm trying to set the health_check_interval of SLB to 30s, and got the error.

 `Error: module.slb-account-web.alicloud_slb.lb: "listener.0.health_check_interval" cannot be higher than 5: 30`

But this can be set in web console up to 50s.

![2017-11-15 12 18 48](https://user-images.githubusercontent.com/4048448/32818636-5b36a2e6-c9ff-11e7-99ac-606714da1cda.png)

5s health_check_interval is too short for us...

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

I am sorry for that. There are some error from API docs. I have fixed the defect and please update the terraform-provider to version 1.2.10, thanks a lot.

Regards,
He Guimin
