### ISSUE TITLE
Support for ap-southeast-3

### ISSUE THREAD

**Issue by oddsocksio** [alibaba/terraform-provider#282]
Is there any chance support could be added for the new Kuala Lumpur region

**Comment by xiaozhu36** [comment]
Hi @oddsocksio 

Thank you for your feedback, we will support Kuala Lumpur region  in the next week. Please be patient, thanks a lot.

Regards
He Guimin

**Comment by xiaozhu36** [comment]
Hi @oddsocksio 

The new provider has supported new Kuala Lumpur region. Please update to [v1.2.11](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.11), thanks a lot.

Regards
He Guimin
