### ISSUE TITLE
Missing examples for how to import dns record

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#283]
I try to check the [doc](http://47.95.33.19:4567/docs/providers/alicloud/r/dns_record.html) for a example to import a alicloud_dns_record, but got no luck.

For the other resources such as ECS, SLB, it would be easy to guess a import example, because the have a explicit id.

But for the DNS record,  that is not easy, probably it has an ID, but it does NOT show on the web console.

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your feedback. I will improve it and now you can use dns name to import a alicloud_dns_record, thanks.

Regards,
He Guimin

**Comment by bittopaz** [comment]
@xiaozhu36 Can you give a short example here, please?
I tried with the dns name, but failed..

**Comment by xiaozhu36** [comment]
@bittopaz 

You can define a dns resource in your template, like `resource "alicloud_dns" "dns" {}` and then run command `terraform import alicloud_dns.dns <your-domain-name>`. Please try again.

**Comment by xiansanluo** [comment]
@bittopaz 
maybe you can get records first,and then you can get the record id.just like this:
data "alicloud_dns_domain_records" "record" {
  domain_name = "xxx.com"
  output_file = "records.txt"
}
exec: terraform plan
cat records.txt

**Comment by bittopaz** [comment]
@xiaozhu36  alicloud_dns is fine, and it works.

But alicloud_dns_record is not that easy...

**Comment by bittopaz** [comment]
@xiansanluo Thanks!
