### ISSUE TITLE
Latest master compilation error -> (type int) as type *int in assignment

### ISSUE THREAD

**Issue by alexwo** [alibaba/terraform-provider#287]
➜  terraform-provider git:(master) make all                                                          
GOOS=darwin GOARCH=amd64 go build -o bin/terraform-provider-alicloud
# github.com/alibaba/terraform-provider/alicloud
alicloud/resource_alicloud_ess_scalinggroup.go:123:16: cannot use d.Get("min_size").(int) (type int) as type *int in assignment
alicloud/resource_alicloud_ess_scalinggroup.go:128:16: cannot use d.Get("max_size").(int) (type int) as type *int in assignment
alicloud/resource_alicloud_ess_scalinggroup.go:133:24: cannot use d.Get("default_cooldown").(int) (type int) as type *int in assignment
alicloud/resource_alicloud_ess_scalinggroup.go:161:10: cannot use d.Get("min_size").(int) (type int) as type *int in field value
alicloud/resource_alicloud_ess_scalinggroup.go:162:10: cannot use d.Get("max_size").(int) (type int) as type *int in field value
alicloud/resource_alicloud_ess_scalinggroup.go:163:18: cannot use d.Get("default_cooldown").(int) (type int) as type *int in field value
make: *** [mac] Error 2

group.go file expects:
	// NOTE: Set MinSize, MaxSize and DefaultCooldown type to int pointer to distinguish zero value from unset value.
	MinSize         *int
	MaxSize         *int
	DefaultCooldown  *int

however, resource_alicloud_ess_scalinggroup.go does not pass int as a pointer

**Comment by xiaozhu36** [comment]
Hi @alexwo 

I am sorry for that. This issue has been fixed. Please update your code and try again, thanks a lot.

Regards
He Guimin
