### ISSUE TITLE
V1.2.11 vswitch.service-net fails with error "unexpected end of JSON input"

### ISSUE THREAD

**Issue by OlegGerber** [alibaba/terraform-provider#289]
The issue occurred on the "eu-central" region.
The detailed error is:

* alicloud_vswitch.bosh: 1 error(s) occurred:

* alicloud_vswitch.bosh: Create subnet got an error :Building CreateVSwitchArgs got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:""}, HostId:"", Code:"AliyunGoClientFailure", Message:"unexpected end of JSON input"}, StatusCode:-1}

The same deployment works well on release V1.2.5

**Comment by xiaozhu36** [comment]
Hi @OlegGerber 

I am sorry for that. There are may be a bug. I have released a new version [v1.3.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.3.0). Please update and try again. Thanks a lot.

Regards,
He Guimin

**Comment by OlegGerber** [comment]
Tested successfully with V1.3.1 release.
Thank you.
