### ISSUE TITLE
SLB creation fails in ap-southeast-3

### ISSUE THREAD

**Issue by oddsocksio** [alibaba/terraform-provider#292]
when trying to create a new SLB in the ap-southeast-3 region terraform fails with the error `Aliyun API Error: RequestId: 0BE381AB-CDF2-49D8-9E42-FDE4C17B8D27 Status Code: 404 Code: InvalidRegionId.NotFound Message: The specified RegionId does not exist.`

example code below

```
provider "alicloud" {
  #   access_key = "${var.access_key}"
  #   secret_key = "${var.secret_key}"
  region = "ap-southeast-3"
}

resource "alicloud_slb" "test" {
  name       = "test"
}
```

**Comment by xiaozhu36** [comment]
Hi @oddsocksio 

Terraform-provider-alicloud has supported ap-southeast-3 from version 1.2.11. Please download and update the latest version, and try again. Thanks a lot.

Regards
He Guimin

**Comment by oddsocksio** [comment]
i was using V1.3.0

**Comment by xiaozhu36** [comment]
Hi @oddsocksio please refer to #294 .
