### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by usualstuff** [alibaba/terraform-provider#30]
Hello Alibaba team,

I'm getting an error when trying to build from source:
```
$ go get ./...
# github.com/alibaba/terraform-provider/alicloud
alicloud/resource_alicloud_slb.go:147: cannot use common.InternetChargeType(v.(string)) (type common.InternetChargeType) as type slb.InternetChargeType in assignment
```

OS: Ubuntu 16.04.1 LTS
Golang: go1.7.4 linux/amd64

Steps to reproduce (via guide from README.md):
```
1) cd $GOPATH
2) mkdir -p src/github.com/alibaba
3) git clone https://github.com/alibaba/terraform-provider.git
4) mv terraform-provider src/github.com/alibaba
5) cd src/github.com/alibaba/terraform-alicloud
6) go get ./...
```

Also, If possible please provide binary for ubuntu x64, because I cannot use binary from http://opensource-tf.oss-cn-shanghai.aliyuncs.com/terraform-provider-alicloud - it's compiled for osx.

By the way, thanks for your efforts to make aliyun accessible with modern tools such as terraform.

Regards,
Alex

**Comment by shuwei-yin** [comment]
@usualstuff , this problem cause Go SDK upgraded, we will fix this bug tomorrow. and we will provide  compiled binary file by ubuntu x64.

Thank you for your patient.

**Comment by usualstuff** [comment]
@shuwei-yin, thank you! Will wait for fix.

**Comment by shuwei-yin** [comment]
@usualstuff  big fixed, and updated readme, please pull it. The ubuntu binary file address is http://tf-linux.oss-cn-shanghai.aliyuncs.com/terraform-provider-alicloud.zip. Currently Terraform supports terraform version ≥ v0.8.2. If have some problem, please feedback, thanks.

**Comment by usualstuff** [comment]
@shuwei-yin, tried right now, binary working. Thank you again! :smile:
