### ISSUE TITLE
alicloud_nat_gateway how to create multiple bandwidth_packages dynamically

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#306]
Hi,

Is it possible to create multiple bandwidth packages in a nat gateway? count is not supported inside an object in the list of the packages. I mean, the following doesn't work:

resource "alicloud_nat_gateway" "nat_gateway" {
  vpc_id = "${alicloud_vpc.vpc.id}"
  spec   = "${var.nat_gateway_spec}"
  name   = "nat-gateway-${var.landscape_name}"
  bandwidth_packages = [{
    count = "${var.num_of_zones}"
    ip_count  = 1
    bandwidth = 200
    zone      = "${element(split(",",var.landscape_zones),count.index)}"
  }]

  depends_on = [
    "alicloud_vswitch.batata",
  ]
}

I also tried to do some manipulations on lists using some of the terraform functions with no luck.

How can this be done?

Thanks!

**Comment by bittopaz** [comment]
I wish they can sperate bandwidth_packages into a dedicated resource, and use a attachment to associate with alicloud_nat_gateway.

**Comment by xiaozhu36** [comment]
Hi @firasnajjar At present, if you want to create multiple bandwidth_packages, you have to define multiple bandwidth_packages in the nat_gateway. As @bittopaz says, we are working on separating bandwidth_packages into a dedicated resource and it will support creating multiple bandwidth_packages dynamically. Please be patient, thanks a lot.

Regards,
He Guimin
