### ISSUE TITLE
Creating nat_gateway fails

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#307]
I tried to create a nat gateway using the following code:

************************************************************************
resource "alicloud_nat_gateway" "nat_gateway" {
  vpc_id = "${alicloud_vpc.vpc.id}"
  spec   = "${var.nat_gateway_spec}"
  name   = "nat-gateway-${var.landscape_name}"
  bandwidth_packages = [{
    ip_count  = 1
    bandwidth = 200
    zone      = "${element(split(",",var.landscape_zones),0)}"
  }]

  depends_on = [
    "alicloud_vswitch.aa",
    "alicloud_vswitch.bb",
    "alicloud_vswitch.cc",
    "alicloud_vswitch.dd"
  ]
}
************************************************************************

Terraform returned the following error:

************************************************************************
1 error(s) occurred:

* alicloud_nat_gateway.nat_gateway: 1 error(s) occurred:

* alicloud_nat_gateway.nat_gateway: CreateNatGateway got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"7DAFDDDF-75C4-46EE-8077-64AF29D2366B"}, HostId:"vpc-openapi-share.eu-central-1.aliyuncs.com", Code:"OrderFailed", Message:"The Account failed to create order."}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
************************************************************************

After that I checked in the console and I saw that the nat gateway was created but the bandwidth_package was not. After that I tried to change the bandwidth to 5 instead of 200. I got the following error:

************************************************************************
Error applying plan:

1 error(s) occurred:

* alicloud_nat_gateway.nat_gateway: 1 error(s) occurred:

* alicloud_nat_gateway.nat_gateway: CreateNatGateway got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"4F53940C-62FF-424B-9D0A-93921D667D4D"}, HostId:"vpc-openapi-share.eu-central-1.aliyuncs.com", Code:"RouterEntryConflict.Duplicated", Message:"A route entry already exists, which CIDR is '0.0.0.0/0'"}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
************************************************************************

**Comment by xiaozhu36** [comment]
Hi @firasnajjar 

I am sorry to tell you that bandwidth packages can not be launched by OpenAPI by using international account. Because your account is international account, at present, you have to launch bandwidth packages via Web console. However, this dilemma won't always exist. New bandwidth packages version will be released in the January and it will resolve the problem. 

Code:"RouterEntryConflict.Duplicated" result from a route entry of which the destination CIDR block is 0.0.0.0/0 already exists in the VRouter of the current VPC. Please Delete the route entry before creating new nat gateway and try again. Thanks a lot.

Regards
He Guimin

**Comment by xiaozhu36** [comment]
HI @firasnajjar The latest version [1.7.1](https://github.com/alibaba/terraform-provider/releases/V1.7.1) has fixed the error that creating nat_gateway fails. The from verison 1.7.1, bandwidth packages has been deprecated, and you can attach several elastic ips to nat gateway. For example: 

    `
    resource "alicloud_eip" "eips" {
         count = 2
         bandwidth = 10
    }

    resource "alicloud_nat_gateway" "gateway" {
      vpc_id = "vpc-2zeluspidpezzkad5rb4b"
      name = "new-gateway"
    }

    resource "alicloud_eip_association" "asso" {
      count = 2
      allocation_id = "${element(alicloud_eip.eips.*.id, count.index)}"
      instance_id = "${alicloud_nat_gateway.gateway.id}"
    }
    `
