### ISSUE TITLE
RDS: switching between "Intranet" and "Internet" for db_instance_net_type doesn't work.

### ISSUE THREAD

**Issue by philippevidal80** [alibaba/terraform-provider#310]
Hello,

**info**: terraform-provider-V1.3.2

I use a RDS (MySQL 5.6) created via Terraform and creation (in "Intranet" net type mode) is OK.

Now, I needed to have access to it from my office.
I added my public IP (in security_ips) and switched from "Intranet" to "Internet".
The IP was correctly added but the switch to "Internet" not realized although Terraform say it's OK... 

```
alicloud_slb.slb-xxxxxxx: Refreshing state... (ID: lb-gs52mqmzosvy4y68hxrai)
alicloud_vpc.vpc-xxxxxxx: Refreshing state... (ID: vpc-t4nin2y8l3gm4f5c025xu)
alicloud_slb_listener.http: Refreshing state... (ID: lb-gs52mqmzosvy4y68hxrai:80)
alicloud_vswitch.vswitch-xxxxxxx: Refreshing state... (ID: vsw-t4n7ksqtejed0wrx0bs2n)
alicloud_security_group.sg-xxxxxxx: Refreshing state... (ID: sg-t4nhlo2i803mlwj78n1b)
alicloud_security_group_rule.sg-xxxxxxx-allow_http_xxxxxxx: Refreshing state... (ID: sg-t4nhlo2i803mlwj78n1b:ingress:tcp:9223/9223:intranet:0.0.0.0/0:accept:1)
alicloud_db_instance.db-xxxxxxx: Refreshing state... (ID: rm-gs5si9d1ag2873mj8)
alicloud_ess_scaling_group.scaling-group-xxxxxxx: Refreshing state... (ID: asg-t4nbhxe3tqh54df2mqdf)
data.template_file.user_data: Refreshing state...
alicloud_ess_scaling_configuration.config-xxxxxxx: Refreshing state... (ID: asc-t4ncnooqnr4gyaz4nlly)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ alicloud_db_instance.db-xxxxxxx
      db_instance_net_type: "Intranet" => "Internet"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_db_instance.db-xxxxxxx: Modifying... (ID: rm-gs5si9d1ag2873mj8)
  db_instance_net_type: "Intranet" => "Internet"
alicloud_db_instance.db-xxxxxxx: Still modifying... (ID: rm-gs5si9d1ag2873mj8, 10s elapsed)
alicloud_db_instance.db-xxxxxxx: Modifications complete after 10s (ID: rm-gs5si9d1ag2873mj8)
```
AliCloud Console indicate an **Intranet** only RDS.
Terraform State indicate an **Intranet** db_instance_net_type.

**Comment by xiaozhu36** [comment]
Hi @philippevidal80 Can you access your database after changing securityIPs?

**Comment by philippevidal80** [comment]
I did not try because on AliCloud Console, no Internet DNS was provided.
The only know URL was internal.

**Comment by xiaozhu36** [comment]
Hi @philippevidal80  I am sorry for that. I guess your RDS instance's network type is VPC. VPC type instance's db_instance_net_type value only is 'Intranet'. So this field can't be changed. This issue is our provider's bug and I will fix it. However, VPC type instance will have public and private network at the same time, and them are showed in the web console. So, you can access your database after changing securityIPs.

**Comment by xiaozhu36** [comment]
Hi @philippevidal80 I have enhanced the RDS function and please update to the lastest version [1.5.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.0) and try again, thanks a lot.
