### ISSUE TITLE
Provide a better error when creating a vswitch

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#315]
By mistake I was trying to create a vswitch using terraform and the vpc_id was an empty string. In this case terraform kept trying to create the resource for 3 minutes then it failed on timeout as it seems with the following error:

* alicloud_vswitch.blabla: Create subnet got an error :Vswitch is still creating result from some unknown error -- try again

It would be great if you can provide a meaningful error in this case stating that the vpc_id cannot be an empty string...

**Comment by xiaozhu36** [comment]
Hi @firasnajjar  Please update to the latest version [1.5.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.0) and it has improved above issue. Thanks a lot.

**Comment by firasnajjar** [comment]
Thanks for your feedback.
