### ISSUE TITLE
Option to specify the private_ip to alicloud instances via terraform 

### ISSUE THREAD

**Issue by alexwo** [alibaba/terraform-provider#316]
Hi,

We have a scenario where we want to control the assigned private IP address for Alicloud instances created by Terraform.

From the official docs it looks that this is only possible to reference a private IP once instances are created:
https://www.terraform.io/docs/providers/alicloud/r/instance.html#private_ip

- Is there an option to specify the IP address for Alicloud instances created via Terraform advance?

Thanks,
Alex

**Comment by xiaozhu36** [comment]
Hi @alexwo Thanks for your feedback. We will support to specify the IP address for Alicloud instances in the next version, and please be patient. Thanks a lot.

**Comment by bittopaz** [comment]
Would love to have this 😄

**Comment by xiaozhu36** [comment]
Hi @alexwo The latest version [1.5.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.0) has supported to specify private ip when creating new VPC instance. Besides, it also support to change existing instance's private_ip and vswitch_id, but it only is valid in the same availability zone. Please update it and have a try. Thanks a lot.
