### ISSUE TITLE
Delete public ip via terraform does not work

### ISSUE THREAD

**Issue by alexwo** [alibaba/terraform-provider#318]
I have tried to use terraform Destroy to remove the public IP that is associated with VM instance.
Terraform was executing around 4m5s and returned the following error:

Error applying plan:
1 error(s) occurred:
* alicloud_eip.jb (destroy): 1 error(s) occurred:
* alicloud_eip.jb: EIP in use - trying again while it is deleted.

**Comment by xiaozhu36** [comment]
Hi @alexwo If EIP has been associated with one ECS instance, it won't be deleted. Please check it.

In addition, we will improve above error including output more useful error message and remove timeout if it can't delete EIP. Please be patient. Thanks a lot.

**Comment by xiaozhu36** [comment]
Hi @alexwo I have output more useful error message and remove timeout if it can't delete EIP in the latest version [1.5.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.0). Please update it. Thanks a lot.
