### ISSUE TITLE
alicloud_route_entry - The request processing has failed due to some unknown error

### ISSUE THREAD

**Issue by alexwo** [alibaba/terraform-provider#319]
Sometimes terraform delete operations fail due to an unknown error.
for instance, in case of deleting route entry, I have recived the below error

Error applying plan:

1 error(s) occurred:

* alicloud_route_entry.nexus (destroy): 1 error(s) occurred:

* alicloud_route_entry.nexus: Deleting RouteEntry got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"2AA18256-D8E4-4AD3-A59F-3D62FF8B2CF0"}, HostId:"ecs-openapi-share.eu-central-1.aliyuncs.com", Code:"UnknownError", Message:"The request processing has failed due to some unknown error."}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Is there a better way to understand the reason for such failures?

**Comment by xiaozhu36** [comment]
Hi @alexwo Which version is your terraform provider? I think this issue has been fixed. Please update to the latest provider [v1.3.3](https://github.com/alibaba/terraform-provider/releases/tag/V1.3.3) and try again. Thanks a lot.

**Comment by xiaozhu36** [comment]
Hi @alexwo  I have enhanced the function that deleting route entry. Please update to the latest version [1.5.0](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.0).  Thanks a lot.
