### ISSUE TITLE
Creating internet-facing load balancer fails

### ISSUE THREAD

**Issue by ninja-at-work** [alibaba/terraform-provider#330]
Hi,

I want to create load balancer with public ip address, but it fails due order error.

Terraform snippet:
```
resource "alicloud_slb" "haproxy-lb" {
  name = "haproxy"
  internet = true
  internet_charge_type = "paybybandwidth"
  bandwidth = 1000
  vswitch_id = "....vswitch id..."
}
```
```
The error itself:
alicloud_slb.haproxy-lb: Creating...
  address:              "" => "<computed>"
  bandwidth:            "" => "1000"
  internet:             "" => "true"
  internet_charge_type: "" => "paybybandwidth"
  name:                 "" => "haproxy"
Error applying plan:

1 error(s) occurred:

* alicloud_slb.haproxy-lb: 1 error(s) occurred:

* alicloud_slb.haproxy-lb: Create load balancer got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"94AF2057-8A0D-4BCB-8944-E9FB8012AA96"}, HostId:"slb.eu-central-1.aliyuncs.com", Code:"OrderFailed", Message:"The Account failed to create order."}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work Internet SLB cannot support to created in one vswitch. You can create a intranet slb in one vswitch and then bind a EIP for it. In addition, terraform will support to bind EIP for slb in the next version. Now, you only use Web console to achieve it. 

Regards
He Guimin

**Comment by ninja-at-work** [comment]
Hi, I tried to remove vswitch_id property (because I don't need it), but the terraform still failing with the following error:
```
alicloud_slb.haproxy-lb: Creating...
  address:              "" => "<computed>"
  bandwidth:            "" => "1000"
  internet:             "" => "true"
  internet_charge_type: "" => "paybybandwidth"
  name:                 "" => "haproxy"
Error applying plan:

1 error(s) occurred:

* alicloud_slb.haproxy-lb: 1 error(s) occurred:

* alicloud_slb.haproxy-lb: Create load balancer got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"C60BC0A5-A2EF-4A2F-BC16-29E1B8788BE1"}, HostId:"slb.eu-central-1.aliyuncs.com", Code:"OrderFailed", Message:"The Account failed to create order."}, StatusCode:400}
```

**Comment by ninja-at-work** [comment]
We have found that terraform is able to create load balancer when internet_charge_type set to `paybytraffic`.
It fails only when internet_charge_type is "paybybandwidth"

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work Do you specify vswitch_id when you creating 'paybytraffic' SLB?

**Comment by ninja-at-work** [comment]
No, I've removed this property, `paybytraffic` option failing always.

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work I have consulted with SLB developing team and I am sorry to tell you that at present, because of some law limitation, SLB can not support alicloud international account to create "paybybandwidth" instance. Your account is international account and you only use 'paybytraffic' SLB. Please forgive it. Thanks a lot.

In addition, I will make some improvement about above error and output more valid inforamation.

Regards
He Guimin
