### ISSUE TITLE
Unable to create blobstorage using terraform in eu-central-1 region

### ISSUE THREAD

**Issue by ninja-at-work** [alibaba/terraform-provider#331]
Hello,

I want to create a blobstorage usign terraform snippet:
```
resource "alicloud_oss_bucket" "bucket" {
  bucket = "my-super-random-id-bucket-123"
  acl = "private"
}
```

It fails due following error:
* alicloud_oss_bucket.bucket: Get http:/?max-keys=1&prefix=my-super-random-id-bucket-123: http: no Host in request URL

I've found in the terraform logs the following message that endpoint for eu-central-1 region is not found:
```
2018-01-08T16:14:40.341Z [DEBUG] plugin.terraform-provider-alicloud: 2018/01/08 16:14:40 Cannot find endpoint in the region: "eu-central-1"
2018-01-08T16:14:40.341Z [DEBUG] plugin.terraform-provider-alicloud: 2018/01/08 16:14:40 [DEBUG] Instantiate OSS client using endpoint: ""
```

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work I am sorry for the issue. It may result from oss service missing endpoint option in region eu-central-1. I will fix it in the next version. Please be patient. Thanks a lot.

Regards
He Guimin

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work The latest version [1.5.3](https://github.com/alibaba/terraform-provider/releases/tag/V1.5.3) has fixed the issue. Please update it and try again, thanks a lot.

Regards,
He Guimin

**Comment by ninja-at-work** [comment]
Thanks, it works
