### ISSUE TITLE
install latest terraform provider not working

### ISSUE THREAD

**Issue by ellerbrock** [alibaba/terraform-provider#341]
hi,

i just found out that there is actually only one terraform provider official available:
https://releases.hashicorp.com/terraform-provider-alicloud/
in version 0.1.0

i wonder why because even on the official terraform provider page its in version 1.5.3 listed:
https://github.com/terraform-providers/terraform-provider-alicloud/releases

my current workaround is to make a hard version:

```
provider "alicloud" {
  version = ">= 1.5.3"

  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}
```

and download the plugin manually, rename it like `terraform-provider-alicloud_v1.5.3_x4` and drop it in the plugins folder, run again a `terraform init` and then it's working ...

but boy oh boy what a workaround.

any ideas why its not directly installable via terraform provider?

cheers maik

**Comment by PEPEInvest** [comment]
yes

**Comment by ellerbrock** [comment]
what you mean, you know what to do?
the [new version](http://47.95.33.19:4567/docs/providers/alicloud/) have so many more features, in case stuff is stable would be nice to get it out to the community ...

![good shit out to the community](https://media.giphy.com/media/Vti5McrcF8N2M/giphy.gif)

**Comment by zhuzhih2017** [comment]
@ellerbrock
We are in the process of resolving this problem.

**Comment by roura356a** [comment]
For me, even using `Terraform v0.11.2` with `provider.alicloud v1.5.3`, I get `provider.alicloud: AccessKeyId cannot be empty!` when I run `terraform plan`.

**Comment by xiaozhu36** [comment]
Hi @roura356a Do you have specified 'access_key' and 'secret_key'? There is two methods to specify them: 
1) specify parameter 'access_key' and 'secret_key' in the provider, like 

        provider "alicloud" {
            access_key = "****"
            secret_key = "****"
        }

2) specify parameter 'ALICLOUD_ACCESS_KEY' and 'ALICLOUD_SECRET_KEY' in you environment parameter.

**Comment by roura356a** [comment]
Yes, I specified them. When I run `terraform plan` I get `provider.alicloud: AccessKeyId cannot be empty`. I tried to reinstall Terraform and the provider but nothing... :/

**Comment by roura356a** [comment]
I Installed `v1.6.0` from releases and I'm still getting the same message :/

**Comment by xiaozhu36** [comment]
Hi @ellerbrock  Terraform provider official version 1.7.0 has been released. Please update it. Thanks a lot.
