### ISSUE TITLE
Error creating security group 

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#346]
Hello,

I cannot create a security group that allows access from another security group on all ports with all protocols. When I run the following:

```
resource "alicloud_security_group_rule" "allow_open_to_test" {
  type = "ingress"
  ip_protocol = "all"
  nic_type = "intranet"
  policy = "accept"
  port_range = "1/65535"
  priority = 1
  security_group_id = "${alicloud_security_group.sg-test.id}"
  source_security_group_id = "${alicloud_security_group.sg-another.id}"
}
```

It fails with the following error: 
* alicloud_security_group_rule.allow_all_udp_internal: 1 error(s) occurred:

* alicloud_security_group_rule.allow_all_udp_internal: Error authorizing security group rule type ingress: Aliyun API Error: RequestId: DCD5C1E8-C2EB-46C4-BFCD-E1BA1AB27371 Status Code: 400 Code: InvalidParam.PortRange Message: Please specify the PortRange or SourcePortRange in integer, less than 65535, and separate the range with ?/?.

I also tried the same rule with tcp protocol only and it fails with the same error.

I use the same port range syntax in another rule that doesn't have source_security_group_id and has a cidr instead and it works. (with tcp protocol only)

Thanks!

**Comment by xiaozhu36** [comment]
HI @firasnajjar I am sorry for your happened. There is a rule that if you want to allow all ports with all protocols, the port_range only is set as "-1/-1". Please update it and try again.

In addition, I will enhance the rule in the next version. Please be patient, thanks a lot.

Regards,
He Guimin

**Comment by firasnajjar** [comment]
Hi @xiaozhu36 ,

Currently we have the following rule:

```
resource "alicloud_security_group_rule" "allow_all_tcp_internal" {
  type = "ingress"
  ip_protocol = "tcp"
  nic_type = "intranet"
  policy = "accept"
  port_range = "1/65535"
  priority = 1
  security_group_id = "${alicloud_security_group.sg-open.id}"
  cidr_ip = "0.0.0.0/0"
}
```

And it's working. So if I understand correctly, only when the rule is about all protocols and all ports we should use -1/-1 and if it is only one protocol and all the ports we use: 1/65535?

Is this the case?

**Comment by xiaozhu36** [comment]
Hi @firasnajjar 

when protocol is `tcp` or `udp`, we can use '1/65535'. Other protocol, like `icmp`, `gre`, `all`, only '-1/-1' can be used. This rule I will enhance in the next version. Please be patient, thanks a lot.

Regards,
He Guimin

**Comment by xiaozhu36** [comment]
Hi @firasnajjar The lastes version [1.6.1](https://github.com/alibaba/terraform-provider/releases/tag/V1.6.1) has avoid the problem. When you creating security group 'all' or 'gre' or 'icmp' rule, the specified 'port_range' will be ignored and its value will be set to '-1/-1'. Please update it and try again. Thanks a lot.

**Comment by firasnajjar** [comment]
HI @xiaozhu36 

Is there an option to provide a port range when using all,gre,icmp or all ports will always be enabled?

Regards,
Firas

**Comment by xiaozhu36** [comment]
HI @firasnajjar 

Thanks for your suggestion. I will consider it and try to improve it in the next version.

Regards
He Guimin

**Comment by xiaozhu36** [comment]
Hi @firasnajjar I have made some improvement about your feedback. The latest version [1.7.0](https://github.com/alibaba/terraform-provider/releases/V1.7.0) set a default "-1/-1" for "port_range" . The value can only be used to all, gre and icmp protocol, and other values will be ignored. "-1/-1" will be ignored when ip protocol is tcp or udp. Please be update and try again. Thanks a lot.
