### ISSUE TITLE
Failed to create RAM user

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#347]
Got the following error message, but I can create RAM users in the web console.

* alicloud_ram_user.sa-users[3]: 1 error(s) occurred:

* alicloud_ram_user.sa-users.3: CreateUser got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"8673D3CC-3EAF-472F-92B3-69C7C0BF07EE"}, HostId:"ram.aliyuncs.com", Code:"Inact
ive", Message:"Account is inactive to this service"}, StatusCode:404}

**Comment by xiaozhu36** [comment]
HI @RainFlying I am sorry for the error. Your account has not open "RAM" service. You have to do it by [Web console](https://ram.console.aliyun.com/#/overview) before using the alicloud_ram* resources.

Regards,
He Guimin

**Comment by RainFlying** [comment]
@xiaozhu36 I have enabled RAM service in the console. I can create RAM user in the web console.

**Comment by RainFlying** [comment]
![Uploading Screenshot 2018-01-17 14.23.08.png…](RAM console)

**Comment by RainFlying** [comment]
@xiaozhu36 Found the reason. I created the access and security key before enabled RAM user. After enabled RAM user, the old access key was invalid. Create new key pair, and terraform works. Thanks.
