### ISSUE TITLE
Alicloud provider doesn't support alicloud_instances data source

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#362]
See the error message:
```
Error: data.alicloud_instances.rechargecenter: Provider doesn't support data source: alicloud_instances
```

According to the doc, it should support this data source.

http://47.95.33.19:4567/docs/providers/alicloud/d/instances.html

Upgraded to v1.7.0, alicloud_instances data source is supported. However, ids attribute are not suported.

```
* output.ecs_rechargecenter: Resource 'data.alicloud_instances.rechargecenter' does not have attribute 'ids' for variable 'data.alicloud_instances.rechargecenter.ids'
```

**Comment by RainFlying** [comment]
OK. Got to know how to get the instance ID now.

You need to use "${data.alicloud_instances.INSTANCE_RESOURCE_NAME.instances.0.id}" to get the id attribute of the first matching instance.

The docs should be consistent with the usage and code.

**Comment by xiaozhu36** [comment]
Hi @RainFlying I am sorry for the misleading information, and I have replenished some information for it. Thanks a lot.
