### ISSUE TITLE
Is ess_scaling_group supporting multiple vswitches?

### ISSUE THREAD

**Issue by xinyifly** [alibaba/terraform-provider#370]
I can add multiple vswitches to `ess_scaling_group` from web console. But only got `vswitch_id` param in terraform resource. Is there an example shows `ess_scaling_group` supporting mutiple vswitches?

**Comment by xiaozhu36** [comment]
Hi @xinyifly Mutiple vswitches will be supported in the next version.  Please be patient. Thanks a lot.

**Comment by xiaozhu36** [comment]
Hi @xinyifly Release [1.7.1](https://github.com/alibaba/terraform-provider/releases/V1.7.1) has supported multiple vswitches. Please update it. Thanks a lot.

**Comment by xinyifly** [comment]
Thank you! I updated to [v1.7.1](https://github.com/alibaba/terraform-provider/releases/V1.7.1) and this issue is fixed.
