### ISSUE TITLE
Notifications on Desktop

### ISSUE THREAD

**Issue by Goose18** [alibaba/terraform-provider#378]
I see that i have a notification from an org, when i click on that org i do not see any notification until i click on Chat. Once i click on chat the notification arrives. I waited for 4 minutes to make sure it was not a delay. I am attaching pictures.

![screenshot 32](https://user-images.githubusercontent.com/17888213/35697457-20755ce2-073f-11e8-9493-2869b0897a6e.png)

![screenshot 31](https://user-images.githubusercontent.com/17888213/35697468-25e580a8-073f-11e8-9074-f85da076ed5f.png)

![screenshot 30](https://user-images.githubusercontent.com/17888213/35697476-29e7a6fe-073f-11e8-8327-47ce734c350d.png)

**Comment by xiaozhu36** [comment]
HI @Goose18 I can not understand the issue. Is it related to the repository?

**Comment by Goose18** [comment]
sorry posted in wrong place.

**Comment by janandjill** [comment]
They want to download a naked video of me
