### ISSUE TITLE
ess_scaling_configuration for intl-account is still default to PayByBandwidth

### ISSUE THREAD

**Issue by xinyifly** [alibaba/terraform-provider#388]
Refer to this commit 246d509d012fda9d6867d4b640ca4008f8c58c7c
Is it supposed to default to `PayByTraffic` for intl-account?

I currently need to add `internet_charge_type = "PayByTraffic"` for `ess_scaling_configuration` to get it work.

**Comment by xiaozhu36** [comment]
HI @xinyifly Thanks for your feedback. At present, ECS instance support 'PayByBandwidth' for intl-account.

**Comment by xinyifly** [comment]
Hi @xiaozhu36 . Then I'm confused that my `ess_scaling_configuration` was failed to create ecs instances yesterday. From the error tips, I changed `internet_charge_type` from `PayByBandwidth` to `PayByTraffic` and it works. On the other side, I can only see `PayByTraffic` option from console when creating ecs instance.

**Comment by janandjill** [comment]
I don't know what the hell is going on either with u hackers but I'm assuming whatever is video is trying to pop on my screen is gonna be humiliating so if all this shit doesn't stop now I am calling the police

**Comment by xiaozhu36** [comment]
Hi @xinyifly yeah, I have confirmed that intl-account only create `PayByTraffic` resource, and I will consider setting InternetChargeType to `PayByTraffic` in the future version.
