### ISSUE TITLE
Failed to create RDS instance: region not found

### ISSUE THREAD

**Issue by RainFlying** [alibaba/terraform-provider#391]
Got the following error message:
```

* alicloud_db_instance.rds: Error creating Alicloud db instance: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"34050946-2BA0-4750-9255-88B0AF89B17B"}, HostId:"rds.aliyuncs.com", Code:"Forbidden.RegionNotFound", Message:"The provided RegionId does not exist in our record. "}, StatusCode:400}
```

I'm using alicloud provider v1.7.1.

The related part of tf file is as following:
```
resource "alicloud_db_instance" "rds" {
  engine               = "${var.engine}"
  engine_version       = "${var.engine_version}"
  instance_type    = "${var.db_instance_type}"
  instance_storage  = "${var.db_instance_storage}"
  instance_charge_type = "${var.db_instance_charge_type}"
  period               = "${var.period}"

  #zone_id = "${var.zone_id}"
  vswitch_id                 = "${var.vswitch_id}"
```
```
provider "alicloud" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}
```
```
variable "region" {
  default = "cn-hongkong"
}
```

Other resources were created successfully.

**Comment by xiaozhu36** [comment]
Hi @RainFlying I am sorry for that. It may be some region don't support. Can you create the specified resource in the region `cn-hongkong` by the web console?

**Comment by xiaozhu36** [comment]
Hi @RainFlying At present, you account may not create the specified resource region `cn-hongkong` may not support your specified resource. Please login web console to ensure supported region. Please be patient, thanks a lot.

**Comment by xiaozhu36** [comment]
HI @RainFlying RDS is not supported in the some zone. Actually, above error results from a invalid availability. Now, version 1.8.0 has supported to retrieve supporting rds zone, and you can refer to the following data source code:

```
data "alicloud_zones" "default" {
      available_resource_creation = "Rds"
}
```

**Comment by xiaozhu36** [comment]
Hi @RainFlying  If the issue still exists, please reopen the issue. Thanks a  lot.
