### ISSUE TITLE
AliCloud Snat Entry creation failing with invalid parameter

### ISSUE THREAD

**Issue by thewookie79** [alibaba/terraform-provider#392]
Hello,

When trying snat_entry creation I get the following error...

* alicloud_snat_entry.snat_b: CreateSnatEntry got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"<ID>"}, HostId:"vpc.aliyuncs.com", Code:"InvalidParameter", Message:"The specified parameter \"%s\" is not valid."}, StatusCode:400}

It appears to be able to find all the necessary parameter id's:
alicloud_snat_entry.snat_b: Creating...
  snat_ip:           "" => "eip-<id>"
  snat_table_id:     "" => "stb-<id>"
  source_vswitch_id: "" => "vsw-<id>"

Also, terraform plan reports no issues/errors when refreshing the state:
  + alicloud_snat_entry.snat_ccs_b
      id:                <computed>
      snat_ip:           "eip<id>"
      snat_table_id:     "stb-<id>"
      source_vswitch_id: "vsw-<id>"

Versions:
Terraform v0.11.3
+ provider.alicloud v1.7.1

**Comment by xiaozhu36** [comment]
Hi @thewookie79 Please specify a valid snat_ip. It should be a valid ip address not eip id.
