### ISSUE TITLE
How can I create multiple vswitch in VPC

### ISSUE THREAD

**Issue by henrycao** [alibaba/terraform-provider#402]
Hello,

I'm doing some testing with terraform. 
I'm using examples/alicloud-vpc to create VPC.
In variables, I follow the default setting,

variable "cidr_blocks" {
  type = "map"
  default = {
    az0 = "10.132.120.0/24"
    az1 = "10.132.121.0/24"
    az2 = "10.132.122.0/24"
  }
}

After the terraform plan, I can only see the very first vswitch. 
How can I create multiple vswitchs ?

**Comment by xiaozhu36** [comment]
HI @henrycao this issue has been updated and please check it. I will close the issue and if you still have any problem, please reopen it. Thanks.
