### ISSUE TITLE
How to create RDS with multi zone on specific VPC or subnet?

### ISSUE THREAD

**Issue by fulgorek** [alibaba/terraform-provider#403]
thats it, how can achieve that?

**Comment by xiaozhu36** [comment]
Hi @fulgorek At present, multi zone will be supported in the next version, and the next version will be released in this week. Please be patient, thanks a lot.

**Comment by xiaozhu36** [comment]
HI @fulgorek release 1.8.1 has supported multi zone. Please update it and try again.

In addition, I will close the PR and if you have other issues, please reopen it.
