### ISSUE TITLE
How can I specify imageid or snapshot for data disk in alicloud_container_cluster?

### ISSUE THREAD

**Issue by teachmyself** [alibaba/terraform-provider#404]

**Comment by xiaozhu36** [comment]
Hi @teachmyself alicloud_container_cluster does not support snapshot while creating cluster. After that, you can use alicloud_disk_attachment to do it. Hope it can help you.

**Comment by xiaozhu36** [comment]
The resource `alicloud_cs_cluster` has been deprecated.
