### ISSUE TITLE
How can I specify user data in alicloud_container_cluster?

### ISSUE THREAD

**Issue by teachmyself** [alibaba/terraform-provider#405]

**Comment by xiaozhu36** [comment]
HI @teachmyself I am sorry to tell you that at present alicloud_container_cluster does not spuuort user data.

**Comment by teachmyself** [comment]
Thank you very much! 
Do you have a plan to support it, and do you have a timeline?

**Comment by xiaozhu36** [comment]
Can you describe your usage scenario details? May be I can give you a solution.

**Comment by xiaozhu36** [comment]
The resource `alicloud_cs_cluster` has been deprecated.
