### ISSUE TITLE
Security groups configuration support

### ISSUE THREAD

**Issue by usualstuff** [alibaba/terraform-provider#41]
Hello Alibaba team,

I'm trying to find any reference in provider that will allow to configure security groups access rules.
As far as I understand, currently there is no support for API that mention in https://intl.aliyun.com/help/doc-detail/25554.htm

Is this true? If so, can you please suggest in what terms you are planning to implement this support?
I find this unfortunate because all other features seems to present.

Thanks,
Alex

**Comment by shuwei-yin** [comment]
@usualstuff yes, the security groups rules haven't support.
we will implement by January 4, then we will reply to you.

Now you may used exists security groups to create instances.  example:

variable "security_groups" {
  type = "list"
  default = ["sg-****"]
}

in resource reference: security_groups = "${var.security_groups}"

**Comment by shuwei-yin** [comment]
@usualstuff , thank you for your patience, the segurity_groups rules already publish, please download the binary file for Utuntu, address: http://tf-linux.oss-cn-shanghai.aliyuncs.com/terraform-provider-alicloud.zip.
please get it, thanks.

**Comment by usualstuff** [comment]
@shuwei-yin, thank you so much! I'll try it when I can.
