### ISSUE TITLE
How can launch a application in alicloud_cs_kubernetes or alicloud_contanier_cluster?

### ISSUE THREAD

**Issue by teachmyself** [alibaba/terraform-provider#425]

**Comment by xiaozhu36** [comment]
Hi @teachmyself new application resource will be supported in the [next version](https://github.com/alibaba/terraform-provider/pull/430). Please be patient. Thanks.

**Comment by xiaozhu36** [comment]
HI @teachmyself The provider version 1.9.1 has supported alicloud_cs_application for swarm cluster. If you want to launch a application in alicloud_cs_kubernetes, you can use [k8s provider](https://www.terraform.io/docs/providers/kubernetes/index.html). Please check it.
