### ISSUE TITLE
How can I apply alert rule to the alilcoud_instance created by terraform?

### ISSUE THREAD

**Issue by teachmyself** [alibaba/terraform-provider#427]

**Comment by xiaozhu36** [comment]
HI @teachmyself Does the alert rule you specified be cloud monitor rule? Can you give more details? Thanks a lot.

**Comment by xiaozhu36** [comment]
Hi @teachmyself The provider 1.9.1 has supported creating cloud monitor rule and it may can meet your requirement. Please check it.
 In addition, I will close the issue and if you have any problem, please reopen it. Thanks.
