### ISSUE TITLE
RDS PostgreSQL type can only create one account and can not destroy it

### ISSUE THREAD

**Issue by georgedriver** [alibaba/terraform-provider#428]
As title with lasted build#ee9074e. Just tested in region us-west-1. Error log as below show:

```
Create db account got an error: &errors.ServerError{httpStatus:400, requestId:"26D0B99D-83F7-47CB-8951-D5EEB69AA0C6", hostId:"rds.aliyuncs.com", errorCode:"QuotaExceeded.AccountName", recommend:"", message:"Account limit exceeded.", comment:""}.

* alicloud_db_account.account: Delete database account got an error: &errors.ServerError{httpStatus:400, requestId:"1B4548E0-D571-4069-A952-10D8EB056EB9", hostId:"rds.aliyuncs.com", errorCode:"IncorrectDBInstanceType.ChildDBInstanceNotSupport", recommend:"", message:"The type of the specified instance does not support this operation.", comment:""}.
```

**Comment by xiaozhu36** [comment]
Hi @georgedriver I am sorry for late reply. Does the issue still exist? Can you reoccur this issue? If so, it will help me to locate the error reason. Thanks a lot.

**Comment by xiaozhu36** [comment]
HI @georgedriver I am sorry for late reply. If your rds instance engine is PostgreSQL, our API does not support to create a postgreSQL database. And you can login the rds instance and to create it manually.
Besides, you can also use [postgreSQL Provider](https://www.terraform.io/docs/providers/postgresql/index.html) to do it.

**Comment by xiaozhu36** [comment]
Hi @georgedriver I will close this issue and if you have any peoblem, please reopen it.
