### ISSUE TITLE
How can I find the supported instance type list?

### ISSUE THREAD

**Issue by zhouxinyu** [alibaba/terraform-provider#431]
Hi,

I find there is a limit for the POSTPaid instances, where can I get the limit rules? Or is it possible to skip the limit while I want to apply some ECSs with good configuration(16c64g+)？And I am able to infer from my tests that the limit is `4c16g`.

```
* alicloud_instance.rmq-broker: 1 error(s) occurred:

* alicloud_instance.rmq-broker: Error creating Aliyun ecs instance: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"EF1D0C2A-AD2D-44E7-AC80-E90E4B1EA8D9"}, HostId:"ecs-cn-hangzhou.aliyuncs.com", Code:"InvalidInstanceType.ValueNotSupported", Message:"The specified instanceType exceeds the maximum limit for the POSTPaid instances."}, StatusCode:400}

```

Let me know if this isn't a right place to raise this question.

**Comment by xiaozhu36** [comment]
Hi @zhouxinyu This issue results from you have no privilege to purchase high-level instance type. So, you have to submit ticket or contact with post sales engineer to apply privilege, and then try again. Thanks a lot.

Regards
Guimin He

**Comment by xiaozhu36** [comment]
HI @zhouxinyu I will close the issue and if you still have any problem, please reopen it. Thanks.
