### ISSUE TITLE
allocate_public_ip deprecation notice confusion

### ISSUE THREAD

**Issue by dperetti** [alibaba/terraform-provider#437]
I get this notice when using allocate_public_ip = false
> "allocate_public_ip": [DEPRECATED] Field 'allocate_public_ip' has been deprecated from provider version 1.6.1. Setting 'internet_max_bandwidth_out' larger than 0 will allocate public ip for instance.

I don't want a public IP, so I tried to follow the recommendation, but if I set `internet_max_bandwidth_out` to 0... then the instance cannot download anything from the internet (which includes downloading a Docker image...)
Having a public IP and being able to download from the internet are two different things.
Please clarify, but it looks like `allocate_public_ip` shouldn't be deprecated !

**Comment by xiaozhu36** [comment]
HI @dperetti I am sorry for late reply. If one instance without public ip or eip, it will not access internet. And, if you want to do it, you can configure a snat for the vswitch in which the instance locates.

**Comment by xiaozhu36** [comment]
HI @dperetti If you still have any problems, please reopen it.
