### ISSUE TITLE
will you support redis(kvstore) for terraform?

### ISSUE THREAD

**Issue by lxitgto** [alibaba/terraform-provider#438]
Hi,

My company use Alicloud almost 1 year and I want to use terraform to manage the infrastructure.

I read the document of terraform/Alicloud-provider. It seems not include redis(kvstore).

**Comment by xiaozhu36** [comment]
HI @lxitgto Welcome to use terraform alibaba cloud provider. At present, kvstore has been in plan and it will be released in the near future. Please be patient, thanks.

**Comment by arafato** [comment]
I'm currently working on an implementation at https://github.com/arafato/terraform-provider/tree/redis Hope to have a first release ready in about 2 weeks.

**Comment by lxitgto** [comment]
@arafato Any update for your PR?

**Comment by arafato** [comment]
@lxitgto it has been submitted at https://github.com/alibaba/terraform-provider/pull/513 and has been already reviewed. I will improve the code according to the comments by the end of this week.

**Comment by lxitgto** [comment]
@arafato are you still working on it?

**Comment by arafato** [comment]
Merge is currently in progress. See https://github.com/alibaba/terraform-provider/pull/587

Currently fixing last review comments.
________________________________

**Comment by arafato** [comment]
@lxitgto finally merged into main branch

**Comment by xiaozhu36** [comment]
Hi @lxitgto @arafato  It has been supported from v1.15.0. Please check it.
