### ISSUE TITLE
Alicloud VPC Express Connect Interconnection

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [alibaba/terraform-provider#448]
I saw the terraform docs https://www.terraform.io/docs/providers/alicloud/index.html, but I cannot find out the way for creating VPC peer connection through express connect.

Is that feature still in backlog? If yes, any ETA on making them live?

Thanks!

**Comment by xiaozhu36** [comment]
Hi @LieAlbertTriAdrian Provider 1.12.0 adds [router interface connection](https://www.terraform.io/docs/providers/alicloud/r/router_interface_connection.html) to connect two router interfaces. Please check it.

In addition, I will close this issue. If you have any problem, please reopen it.
