### ISSUE TITLE
EIP支持预付费吗

### ISSUE THREAD

**Issue by ycsk02** [alibaba/terraform-provider#449]
通过alicloud_eip创建EIP，创建的是后付费方式，文档中没有付费方式的设置，EIP支持预付费吗？

**Comment by xiaozhu36** [comment]
Hi @ycsk02 你好，非常抱歉，目前还不支持。

**Comment by xiaozhu36** [comment]
@ycsk02 你好，provider 1.10.1 已经支持创建预付费的EIP，请检查。另外，我要把这个issue关了，如果还有问题，请重新打开这个issue。
