### ISSUE TITLE
Alicloud create mongoDB and Redis

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [alibaba/terraform-provider#450]
I saw the terraform docs https://www.terraform.io/docs/providers/alicloud/index.html, but I cannot find out the way for creating MongoDB and Redis.

Is that feature still in backlog? If yes, any ETA on making them live?

Thanks!

**Comment by LieAlbertTriAdrian** [comment]
Any updates on this?

**Comment by xiaozhu36** [comment]
HI @LieAlbertTriAdrian  I am sorry for late reply. I am try my best to do it. Please be patient.  Thanks.

**Comment by LieAlbertTriAdrian** [comment]
Thanks, any ETA on when will this be supported? @xiaozhu36

**Comment by arafato** [comment]
@xiaozhu36 I could help with that in case you can't prioritize. Let me know if I can step in.

**Comment by xiaozhu36** [comment]
HI @LieAlbertTriAdrian The release 1.37.0 has supported MongoDB and release 1.15.0 has supported Redis. Please check them.
