### ISSUE TITLE
SLB With Multiple Listeners Causes OperationBusy Error

### ISSUE THREAD

**Issue by scult** [alibaba/terraform-provider#451]
Hi there,

I'm creating an SLB attaching an EIP and creating 3 listeners for it. All of this is working fine. The SLB is created, the EIP is attached and the listeners are created.

However when I try to run ``` terraform apply``` again I get the following error during the refresh phase for 2 of the 3 load balancing rules:

* alicloud_slb_listener.app-ssh: alicloud_slb_listener.app-ssh: DescribeLoadBalancerTCPListenerAttribute got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"5EAC500B-1490-4960-AB48-1CB6EC3DD0C7"}, HostId:"slb-pop.aliyuncs.com", Code:"OperationBusy", Message:"A previous operation is pending."}, StatusCode:400}

This also happens when trying to destroy the environment, which means you either have to manually remove references to rules from your terraform.tfstate or just throw away terraform.tfstate all together and delete the environment manually.

**Comment by xiaozhu36** [comment]
HI @scult I am sorry for late reply. This issue has been fixed by release 1.9.2. Please be check it. 
I will close the PR and if the issue still exist, please reopen it. Thanks a lot.
