### ISSUE TITLE
 'alicloud_cs_kubernetes.main' does not have attribute

### ISSUE THREAD

**Issue by seitosan** [alibaba/terraform-provider#454]
Hello 

I have some issue with  'alicloud_cs_kubernetes'. 

I define two outputs : 
```
output "apiserverIp" {
  value = "${alicloud_cs_kubernetes.main.connections.api_server_internet}"
}

output "master_public_ip" {
  value = "${alicloud_cs_kubernetes.main.connections.master_public_ip}"
}
```

but it return : 

Error: Error running plan: 2 error(s) occurred:

* output.apiserverIp: Resource 'alicloud_cs_kubernetes.main' does not have attribute 'connections.api_server_internet' for variable 'alicloud_cs_kubernetes.main.connections.api_server_internet'
* output.master_public_ip: Resource 'alicloud_cs_kubernetes.main' does not have attribute 'connections.master_public_ip' for variable 'alicloud_cs_kubernetes.main.connections.master_public_ip'

Can you help me ?

best regards

**Comment by xiaozhu36** [comment]
HI @seitosan You can try to use join("", alicloud_cs_kubernetes.main.*.connections.master_public_ip)

**Comment by seitosan** [comment]
Hi @xiaozhu36  i have some issue with timeout. I can't test again at this time
