### ISSUE TITLE
alicloud_cs_kubernetes.main

### ISSUE THREAD

**Issue by seitosan** [alibaba/terraform-provider#455]
Hi 

i have some issue with the provisionning of cs_kubernetes.

terraform -v
Terraform v0.11.7
+ provider.alicloud v1.9.1

this is my code  : 

```
resource "alicloud_vpc" "k8svpc" {
  name       = "k8svpc"
  cidr_block = "192.168.0.0/16"
}

resource "alicloud_vswitch" "vsw" {
  vpc_id            = "${alicloud_vpc.k8svpc.id}"
  cidr_block        = "192.168.1.0/24"
  availability_zone = "${var.availability_zone}"
  name              = "k8sswitch"
  description       = "Switch for k8s cluster"
}

resource "alicloud_cs_kubernetes" "main" {
  name                  = "${var.k8sname}"
  availability_zone     = "${var.availability_zone}"
  new_nat_gateway       = true
  worker_number         = 1
  worker_instance_type  = "ecs.n4.small"
  master_instance_type  = "ecs.n4.small"
  password              = "${var.sshpwd}"
  pod_cidr              = "172.20.0.0/16"
  service_cidr          = "172.21.0.0/20"
  enable_ssh            = true
  install_cloud_monitor = true
  vswitch_id            = "${alicloud_vswitch.vsw.id}"
}


```

sometimes I have this error message : 

Error: Error applying plan:

1 error(s) occurred:

* alicloud_cs_kubernetes.main: 1 error(s) occurred:

* alicloud_cs_kubernetes.main: Waitting for kubernetes cluster "running" got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:""}, HostId:"", Code:"AliyunGoClientFailure", Message:"Timeout"}, StatusCode:-1}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

How can I solved the timeout problem ? 

best regards

**Comment by xiaozhu36** [comment]
Hi @seitosan I am sorry for late reply. This issue has been fixed by release 1.9.2. Please check it. I will close it and if the issue still exist, please reopen it, thanks.

**Comment by seitosan** [comment]
Hi @xiaozhu36  

I have the same issue in 1.9.2


```
terraform version
Terraform v0.11.7
+ provider.alicloud v1.9.2
```

```
 provider.alicloud: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://ecs-cn-hangzhou.aliyuncs.com?AccessKeyId=LTAIyHXkPIqdVll4&Action=DescribeRegions&Format=JSON&RegionId=eu-central-1&SignatureMethod=HMAC-SHA1&SignatureNonce=pdtProFAqUYMlfxIKYGPInrRh3jCwj5g&SignatureVersion=1.0&Timestamp=2018-05-21T13%3A23%3A57Z&Version=2014-05-26&Signature=X%2B2%2Fe6ZrN5SFotpSKWfdanS743E%3D: dial tcp 106.11.61.112:443: i/o timeout

```

**Comment by xiaozhu36** [comment]
I am sorry for that. This is another issue and this issue result from bad network environment. At present, you have to try again to fix it. But, I will try my best in the next version.
