### ISSUE TITLE
Change hostname failed with success infromation.

### ISSUE THREAD

**Issue by teachmyself** [alibaba/terraform-provider#457]
What's changed in terraform config file:
![1](https://user-images.githubusercontent.com/3043256/39510145-34f3baf6-4e1b-11e8-88af-f8c6d6d2899a.jpg)

Terraform said changed successful, but only instance name changed, hostname was not.

**Comment by xiaozhu36** [comment]
Hi @teachmyself I am sorry for late reply. Host name can be effect after the instance is restarted. This issue have been fixed by version 1.9.2. Please be check it. 
I will close the issue and if the issue still exists, please reopen it. Thanks.
