### ISSUE TITLE
Aliyun API Error: RequestId:  Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check

### ISSUE THREAD

**Issue by tomnology** [alibaba/terraform-provider#479]
Currently facing the following error when trying to connect to the alibaba cloud with windows environment.

ENV are set:
```
ALICLOUD_ACCESS_KEY
ALICLOUD_SECRET_KEY

```
.exe is installed to the same DIR where terraform is installed. 

Created a "terraformrc" file which contains:

```
 providers {
 alicloud = "C:/Terraform/terraform-provider-alicloud"
 }
```

Error message when exeuting "terraform plan":

Error: Error refreshing state: 1 error(s) occurred:

* provider.alicloud: Aliyun API Error: RequestId:  Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check

**Comment by xiaozhu36** [comment]
Close for no reply.
