### ISSUE TITLE
Updating ESS scaling configuration

### ISSUE THREAD

**Issue by otarabai** [alibaba/terraform-provider#497]
Hi,

I have the following ESS scaling group setup:

```
resource "alicloud_ess_scaling_group" "main" {
  max_size           = "${var.esg_max_size}"
  min_size           = "${var.esg_min_size}"
  loadbalancer_ids   = ["${alicloud_slb.main.id}"]
  removal_policies   = ["OldestScalingConfiguration", "OldestInstance"]
  scaling_group_name = "${var.env}-${var.app_name}-esg"
  vswitch_ids        = [
      "${data.terraform_remote_state.vpc.vswitch_app_a_id}",
      "${data.terraform_remote_state.vpc.vswitch_app_b_id}"
  ]
}

resource "alicloud_ess_scaling_configuration" "main" {
  active               = true
  enable               = true
  force_delete         = true
  image_id             = "${data.alicloud_images.main.images.0.id}"
  instance_name        = "${var.env}-${var.app_name}-inst"
  instance_type        = "${var.instance_type}"
  internet_charge_type = "PayByTraffic"
  key_name             = "${var.key_name}"
  scaling_group_id     = "${alicloud_ess_scaling_group.main.id}"
  security_group_id    = "${alicloud_security_group.instance.id}"
  system_disk_category = "${var.disk_category}"
  user_data            = "${var.user_data}"

  tags {
    Name  = "${var.env}-${var.app_name}-inst"
    Owner = "${var.owner}"
  }
}
```

After changing anything on the scaling configuration (for example user data), this triggers the re-creation of the scaling configuration. Eventually I get the error `The specified scaling group does not exist.`, I assume because `force_delete = true` deletes the scaling group as well. I have to run `terraform apply` again to create a new scaling group and config, this is not very practical.

If I remove the `force_delete = true`, the scaling group is not deleted but I get the error `You cannot delete a scaling configuration or scaling group while there is instance associated with it.` because it tries to delete the old scaling configuration.

What is the recommended way to have reliable changes to scaling configuration? Also, is there any way to have rolling updates similar to AWS ASG, i.e. creates new instances with the new config, waits until they are healthy, then destroy the old instances and the old config?

Thanks!

**Comment by xiaozhu36** [comment]
HI @otarabai The release 1.43.0 has fixed it. Please check it.
