### ISSUE TITLE
Missing features from SLB listener

### ISSUE THREAD

**Issue by otarabai** [alibaba/terraform-provider#539]
Can you please add support for creating listeners that use a VServer Group instead of the default backend servers?

**Comment by otarabai** [comment]
Another feature missing from SLB listener: Creation of HTTP-to-HTTPs redirect listener. Using the cli, that is done using the parameters `--ListenerForward` and `--ForwardPort`.

**Comment by xiaozhu36** [comment]
Hi @otarabai I am sorry for late reply. The second feature has been fixed by 1.40.0. What do you mean the first feature?

**Comment by xiaozhu36** [comment]
@otarabai Is there any update?

**Comment by otarabai** [comment]
Thanks @xiaozhu36 The first issue was a misunderstanding. Thanks for fixing the second one. I will close the issue.
