### ISSUE TITLE
Terraform not correctly setting "nic_type" for security group rule

### ISSUE THREAD

**Issue by usualstuff** [alibaba/terraform-provider#54]
Hello Alibaba team,

When creating security group role, terraform always sets "nic_type" to "intranet".

For example:
main.tf:
```
resource "alicloud_security_group_rule" "ssh" {
  type = "ingress"
  ip_protocol = "tcp"
  nic_type = "internet"
  policy = "accept"
  port_range = "22/22"
  priority = "1"
  security_group_id = "${alicloud_security_group.sg.id}"
  cidr_ip = "0.0.0.0/0"
}
```

Terraform execution:
```
  cidr_ip:           "" => "0.0.0.0/0"
  ip_protocol:       "" => "tcp"
  nic_type:          "" => "internet"
  policy:            "" => "accept"
  port_range:        "" => "22/22"
  priority:          "" => "1"
  security_group_id: "" => "sg-2ze7hw1sj9szm09q2c4a"
  type:              "" => "ingress"
```

Terraform plan after creation:
```
    cidr_ip:           "0.0.0.0/0" => "0.0.0.0/0"
    ip_protocol:       "tcp" => "tcp"
    nic_type:          "intranet" => "internet" (forces new resource)
    policy:            "accept" => "accept"
    port_range:        "22/22" => "22/22"
    priority:          "1" => "1"
    security_group_id: "sg-2ze7hw1sj9szm09q2c4a" => "sg-2ze7hw1sj9szm09q2c4a"
    type:              "ingress" => "ingress"
```

Also, I was able to confirm this after reviewing new rule in ECS Managment Console: I see new rule in tab "intranet ingress".

Please fix this.

Thanks,
Alex

**Comment by wangyuelucky** [comment]
Hi, @usualstuff  Thanks for getting in touch here.
The "nic_type" will always be "intranet" when you set vpc_id to security group, according to ecs product.
Refer to https://intl.aliyun.com/help/doc-detail/25554.htm

wangyuelucky

**Comment by usualstuff** [comment]
@wangyuelucky, oh, okay, understood. Sorry for trouble: docs sometimes could be kinda confusing.

Thanks for you time,
Alex
