### ISSUE TITLE
No multi-zones returned for eu-central-1 region

### ISSUE THREAD

**Issue by merckm-cr** [alibaba/terraform-provider#546]
Using the alicloud_zones data source with the configuration below does not return a MultiAZ zone for RDS instances for the eu-central-1 (Frankfurt) region. 

data "alicloud_zones" "main" {
  multi = true
  output_file  = "rds-zones.txt"
}

This zone is however available and can be retrieved with the following CLI command:
 
aliyun rds DescribeRegions | jq . 
{
  "RequestId": "8812B846-1410-4982-AEB6-732B105AE8D2",
  "Regions": {
    "RDSRegion": [
      {
        "RegionId": "eu-central-1",
        "ZoneId": "eu-central-1a"
      },
      {
        "RegionId": "eu-central-1",
        "ZoneId": "eu-central-1MAZ1(a,b)"
      },
    ]
  }
}

I removed the other regions for readability.

**Comment by xiaozhu36** [comment]
Hi  @merckm-cr You need to add another field "available_resource_creation" and set it to 'Rds'. As following:
```
data "alicloud_zones" "main" {
    available_resource_creation = "Rds"
    multi = true
    output_file = "rds-zones.txt"
}
```
