### ISSUE TITLE
Need support dns private zone 

### ISSUE THREAD

**Issue by kineta-Jiang** [alibaba/terraform-provider#550]
terraform-provider did not support dns privatezone, it will be nice support dns private zone

**Comment by bittopaz** [comment]
Please consider to support this. @xiaozhu36

**Comment by xiaozhu36** [comment]
HI @kineta-Jiang @zhuzhaoyuan I am trying to do that. Please be patient.

**Comment by xiaozhu36** [comment]
HI @kineta-Jiang @bittopaz It has been supported from v1.14.0. Please check it.
