### ISSUE TITLE
Can't create Event Triggered Scaling Tasks

### ISSUE THREAD

**Issue by merckm-cr** [alibaba/terraform-provider#564]
We would like to create event triggered scaling tasks from Terraform.
Specifically we would like to create scaling rules which scale up or down the cluster on metrics like CPUUtilization. This is currently not possible, as only alicloud_ess_schedule elements can be created.

**Comment by xiaozhu36** [comment]
HI @merckm-cr I am sorry for late reply. Release 1.15.0 has supported it and you can use resource `alicloud_ess_alarm` to do that.

**Comment by xiaozhu36** [comment]
Fixed and Closed.
