### ISSUE TITLE
provider.alicloud: [SDK.CanNotResolveEndpoint] Can not resolve endpoint

### ISSUE THREAD

**Issue by hqq718685** [alibaba/terraform-provider#612]
* provider.alicloud: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Ecs","RegionId":"cn-qingdao","LocationProduct":"ecs","LocationEndpointType":"openAPI"}), please check the user guide

**Comment by hqq718685** [comment]
[root@localhost opt]# terraform apply

Error: Error refreshing state: 1 error(s) occurred:

* provider.alicloud: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Ecs","RegionId":"cn-qingdao","LocationProduct":"ecs","LocationEndpointType":"openAPI"}), please check the user guide

**Comment by xiaozhu36** [comment]
HI @hqq718685 This error comes from you specified a incorrect access key or secret key. Please check them.

**Comment by xiaozhu36** [comment]
HI @hqq718685 I will close this pr and if your problem still exists, please reopen it.
