### ISSUE TITLE
support Datahub

### ISSUE THREAD

**Issue by kuien** [alibaba/terraform-provider#644]
We wanna support Datahub management within terraform.

Datahub's golang version sdk is ready on: https://github.com/aliyun/aliyun-datahub-sdk-go

Following is a short description of Datahub.

> DataHub is a real-time data distribution platform designed to process streaming data. It offers features such as publish, subscribe, and distribute streaming data. It helps to easily analyze and create applications based on streaming data.
>
> Based on Alibaba Cloud’s Apsara platform, DataHub delivers high availability, low latency, high scalability, and high throughput. Seamlessly connected to Alibaba Cloud’s stream computing engine, StreamCompute, DataHub allows you to use SQL to analyze streaming data. It can also distribute streaming data to various cloud products, such as MaxCompute (formerly known as ODPS) and OSS.

**Comment by xiaozhu36** [comment]
Thanks a lot for your contributions. The datahub resources have been published in the 1.19.0. Please check it.
