### ISSUE TITLE
Support `connection_timeout` in SLB

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#674]
![2018-09-07 5 39 58](https://user-images.githubusercontent.com/4048448/45211617-5938db80-b2c5-11e8-816c-0000e8c9ffc1.png)

Please consider to support this `connection_timeout` argument.

**Comment by xiaozhu36** [comment]
Fixed

**Comment by bittopaz** [comment]
Thanks @xiaozhu36
