### ISSUE TITLE
NAT Gateway usage example

### ISSUE THREAD

**Issue by usualstuff** [alibaba/terraform-provider#69]
Hello alibaba team,

I'm not sure if I'm asking in the right place, but it would be very nice if you could explain how exactly I should use NAT gateway via terraform.

Now I'm using it like this:
```
resource "alicloud_nat_gateway" "main" {
  vpc_id = "${alicloud_vpc.main.id}"
  spec = "Small"
  bandwidth_packages = [
    {
      ip_count = 1
      bandwidth = 5
      zone = "${var.availability_zone}"
    }
  ]
  depends_on = [
    "alicloud_vswitch.main"]
}
```

As expected, vrouter for vpc was modified with default route of nat gateway but it's not seems to work.
Am I missing something? I could not find any documentation of nat gateways either in aliyun console or api reference.

Thanks,
Alex

**Comment by wangyuelucky** [comment]
I am sorry that NAT Gateway is not avilable for overseas users by now.
Optionally, we will support config NAT-Based VPC environment by ecs UserData next week.

Can you bypass the problem in other ways? We will inform you of the new progress as soon as possible.

Thanks for the report.

**Comment by usualstuff** [comment]
@wangyuelucky, thank you quick response.
I guess I'll need to create and configure NAT instance manually then or allocate external IP for every instance, which is very unfortunate.
Thanks anyway. I looking forward for more cloud-native solution from you guys.

Regards,
Alex

**Comment by wangyuelucky** [comment]
@usualstuff  As we all know, Alicloud is on the way to Internationalization, more and more products will follow up soon after.Please give us a little time :)


Thans for your attention and support! Any advice is welcome!

**Comment by wangyuelucky** [comment]
Hi @usualstuff, we have published a new version yesterday, mainly we add some data source and fix some bugs.

Need to point is that we change ecs paramter 'io_optimized' from optional to required to avoid unexpected buy constraints. When your update your binary file, be sure it would not crush your project.

Thanks

**Comment by usualstuff** [comment]
@wangyuelucky, thank you for the efforts, it's really important to our team.

Cool, will check out new version. 

Regards,
Alex

**Comment by wangyuelucky** [comment]
any suggestion will be appreciated :)

**Comment by wangyuelucky** [comment]
Hi @usualstuff 

We hava upload the sample of  create and configure NAT instance.Hope to be useful to you.

refer https://github.com/alibaba/terraform-provider/tree/dev/terraform/examples/alicloud-ecs-nat

Thanks

**Comment by usualstuff** [comment]
@wangyuelucky, thank you for contribution!
Though, this is not exactly what we need: single nat instance always will be one of those single point of failure that we try to avoid. What we need is nat-as-a-service (which called nat gateway in AWS), because it's actually more than one node.

Thanks,
Alex

**Comment by wangyuelucky** [comment]
@usualstuff  I am sure what you realy need. 

Although alicloud has the same solution called Nat Gateway, it is not  avilable for overseas users.
And I have proposed to the relevant team to accelerate product output overseas.


Thanks,
YueWang

**Comment by usualstuff** [comment]
@wangyuelucky, thank you so much for your commitment! Looking forward for this feature :)

**Comment by wangyuelucky** [comment]
My pleasure! :)

**Comment by xiaozhu36** [comment]
Hi @usualstuff 

Thank you for your patience. Nice to notice you that today Nat Gateway has been online and available for overseas users. Please have a try and if you happen any problem, contact me, thanks.

Regards,
He Guimin
