### ISSUE TITLE
example for vpc with 3different az vswitchs

### ISSUE THREAD

**Issue by gowrisankar22** [alibaba/terraform-provider#698]
Hello Colleagues,

I could not find examples for a vpc with 3 v-switches in different availability zones and it should be added to the route table and all v-switches should be added to a nat gateway for the public subnet.

BRs, Gowrisankar

**Comment by xh4n3** [comment]
Please have a look at `const testAccContainerMultiAZKubernetes_basic` at https://github.com/alibaba/terraform-provider/blob/master/alicloud/resource_alicloud_cs_kubernetes_test.go
I will make one example shortly.

**Comment by gowrisankar22** [comment]
Thanks @xh4n3... Let me know once you make the example.

**Comment by xiaozhu36** [comment]
Hi @gowrisankar22 @xh4n3 The existing example/kubernetes has supported  3 v-switches in different availability zones. Please check it.

**Comment by xiaozhu36** [comment]
Hi @gowrisankar22 @xh4n3 I will close this issue. If your problem still exist, please reopen it.

**Comment by gowrisankar22** [comment]
I have created a PR for #742 @xh4n3 @xiaozhu36  can you have a look at it ?
