### ISSUE TITLE
alicloud_cs_kubernetes ignoring new_nat_gateway = false

### ISSUE THREAD

**Issue by em-schmidt** [alibaba/terraform-provider#707]
Creating a kubernetes cluster wtih following spec: 

alicloud_cs_kubernetes.k8s_cluster: Creating...
  availability_zone:       "" => "<computed>"
  connections.%:           "" => "<computed>"
  enable_ssh:              "" => "true"
  image_id:                "" => "<computed>"
  install_cloud_monitor:   "" => "false"
  key_name:                "" => "test-key"
  master_disk_category:    "" => "cloud_ssd"
  master_disk_size:        "" => "40"
  master_instance_types.#: "" => "1"
  master_instance_types.0: "" => "ecs.sn2ne.xlarge"
  master_nodes.#:          "" => "<computed>"
  name:                    "" => "<computed>"
  name_prefix:             "" => "test-k8s"
  nat_gateway_id:          "" => "<computed>"
  new_nat_gateway:         "" => "false"
  pod_cidr:                "" => "172.16.0.0/16"
  security_group_id:       "" => "<computed>"
  service_cidr:            "" => "172.19.0.0/20"
  slb_id:                  "" => "<computed>"
  slb_internet:            "" => "<computed>"
  slb_intranet:            "" => "<computed>"
  vpc_id:                  "" => "<computed>"
  vswitch_ids.#:           "" => "1"
  vswitch_ids.0:           "" => "vsw-k1afcksz2xbq7o9ac9ztt"
  worker_disk_category:    "" => "cloud_ssd"
  worker_disk_size:        "" => "40"
  worker_instance_types.#: "" => "1"
  worker_instance_types.0: "" => "ecs.sn2ne.xlarge"
  worker_nodes.#:          "" => "<computed>"
  worker_numbers.#:        "" => "1"
  worker_numbers.0:        "" => "3"

Over the wire API call to cs.aliyuncs.com 
{
    "cluster_type": "Kubernetes",
    "container_cidr": "172.16.0.0/16",
    "disable_rollback": true,
    "key_pair": "test-key",
    "master_instance_type": "ecs.sn2ne.xlarge",
    "master_system_disk_category": "cloud_ssd",
    "master_system_disk_size": 40,
    "name": "test-k8s20181002212425677000000010",
    "num_of_nodes": 3,
    "service_cidr": "172.19.0.0/20",
    "ssh_flags": true,
    "stack_params": {},
    "timeout_mins": 60,
    "vpcid": "vpc-k1a3wmfulrs02f7gk4s0q",
    "vswitchid": "vsw-k1afcksz2xbq7o9ac9ztt",
    "worker_instance_type": "ecs.sn2ne.xlarge",
    "worker_system_disk_category": "cloud_ssd",
    "worker_system_disk_size": 40,
    "zoneid": "ap-southeast-5a"
}

Note that the snat_entry is not set to false in the cs api call.

**Comment by mehemken** [comment]
On the Aliyun side this results in a failed resource because of this:
```
Resource Name: k8s_NAT_Gateway
Resource ID: k8s_NAT_Gateway
Physical ID： -
Resource Type: ALIYUN::ECS::NatGateway
Time Updated: 2018-10-05 12:27:20
Status：Creation failed
Status Description: ResponseException: resources.k8s_NAT_Gateway: A route entry already exists, which CIDR is '0.0.0.0/0' Code: RouterEntryConflict.Duplicated RequestId: 542C1FD1-A8E5-4575-888A-CC9A2B26F360
```

The failure also causes `terraform plan`, `terraform apply`, `terraform destroy` etc... to time out. It is the same behavior as in issue #706 .

**Comment by em-schmidt** [comment]
fixed in https://github.com/terraform-providers/terraform-provider-alicloud/pull/410
