### ISSUE TITLE
Cannot create more than one kubernetes cluster in a single VPC

### ISSUE THREAD

**Issue by mehemken** [alibaba/terraform-provider#723]
Creation of more than one k8s cluster fails if they use the same VPC

```
* module.second_cluster.alicloud_cs_kubernetes.k8s_cluster: 1 error(s) occurred:

* alicloud_cs_kubernetes.k8s_cluster: Creating Kubernetes Cluster got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"D4EE45E5-69A9-453A-82B6-F1D98780FB8B"}, HostId:"", Code:"InstanceRouterExist", Message:" 0.0.0.0/0 route entry already exist"}, StatusCode:400}
```

That route cannot be deleted.

**Is there a workaround for this?**

**Comment by xh4n3** [comment]
@mehemken 
new_nat_gateway is enabled by default, when you are creating the second cluster, you need to disable this option. Then it will not try to create a route entry for you.

**Comment by mehemken** [comment]
Hi @xh4n3 thanks for the feedback. I have tried that and the creation fails. It still tries to create another NAT gateway but it fails to do so. The ultimate result is that the cluster gets created, but it is in a failed state.

Last week I was able to create two clusters. However, the `new_nat_gateway` setting needed to be set to `true` for both clusters. The code that ran successfully as recently as last Friday, now does not work. I have tried every combination of true/false for that setting, as well as creating a `alicloud_nat_gateway` first and then the k8s clusters. I have been unable to create two clusters in the same VPC this week.

I can paste the error message I get when creating the second cluster here. I'm currently creating a k8s cluster and it will take about 20 more minutes before that one finishes and I can create the second one.

[ERROR coming soon]

**Comment by mehemken** [comment]
# Output below is relevant to this issue

The second `alicloud_cs_kubernetes` cluster has built and is in a failed state. Expand below to see the current state as shown by the `terraform state show <resource>` command. (**Note**: `new_nat_gateway` is set to `false`)

<details>
<summary> terraform state show </summary>
<pre>
<code>
✗ terraform state show module.aux_cluster.alicloud_cs_kubernetes.k8s_cluster
id                      = as6d51z3dsf3dz1f6a5sd4fd
availability_zone       = cn-shanghai-c
cluster_ca_cert         = cert.pem.file
cluster_network_type    = flannel
enable_ssh              = true
install_cloud_monitor   = false
key_name                = key_name
master_disk_category    = cloud_efficiency
master_disk_size        = 40
master_instance_types.# = 1
master_instance_types.0 = ecs.n4.small
name                    = cluster-name
name_prefix             = Terraform-Creation
new_nat_gateway         = false
pod_cidr                = 192.168.x.x/xx
service_cidr            = 192.168.x.x/xx
vswitch_ids.#           = 1
vswitch_ids.0           = vsw-sdfa3s51dz3s5dz46d
worker_disk_category    = cloud_efficiency
worker_disk_size        = 50
worker_instance_types.# = 1
worker_instance_types.0 = ecs.n4.small
worker_numbers.#        = 1
worker_numbers.0        = 3
</code>
</pre>
</details>

---

The Alicloud console shows that this cluster failed to create for the following reason. Expand below.

<details>
<summary> debug output </summary>
<pre>
<code>
Reasons for cluster creation failure : Repeatedly creating a gateway

Resource CREATE failed: ResponseException: resources.k8s_NAT_Gateway: A route entry already exists, which CIDR is '0.0.0.0/0' Code: RouterEntryConflict.Duplicated RequestId: 9D175E56-5077-465C-8F61-70BF4E38DF59:

</code>
</pre>
</details>
<br>

The console also shows which stack resources failed to create

![image](https://user-images.githubusercontent.com/16868431/46832222-59137c00-cd5a-11e8-8366-98b60a4a2875.png)

<details>
<summary> Response Exception detail </summary>
<pre>
<code>

ResponseException: resources.k8s_NAT_Gateway: A route entry already exists, which CIDR is '0.0.0.0/0' Code: RouterEntryConflict.Duplicated RequestId: 9D175E56-5077-465C-8F61-70BF4E38DF59

</code>
</pre>
</details>

---

# Output below is relevant to issue #706 

Below is the output of `terraform plan`. This happens after every time a resource fails to create. For me that is mostly a kubernetes cluster, but it has happened with other resources. The workflow to reporduce would be thus:

1. Create a resource (in this case k8s)
1. The resource fails to create
1. Try `terraform plan`
1. Error below is reproduced

<details>
<summary> terraform plan </summary>
<pre>
<code>

✗ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

...
...
alicloud_cs_kubernetes.k8s_cluster: Refreshing state... (ID: zdf3s5d1f3s5f46zsdfzsddf13s5d1f3zsdf)
alicloud_cs_kubernetes.k8s_cluster: Refreshing state... (ID: zdf3s5d1f3s5f46zsdfzsddf13s5d1f3zsdf)

Error: Error refreshing state: 1 error(s) occurred:

* module.aux_cluster.alicloud_cs_kubernetes.k8s_cluster: 1 error(s) occurred:

* module.aux_cluster.alicloud_cs_kubernetes.k8s_cluster: alicloud_cs_kubernetes.k8s_cluster: [ERROR] There is no any nodes in kubernetes cluster cfcb88d21ef90472881a30bb4f438f150.

</code>
</pre>
</details>

**Comment by xh4n3** [comment]
@mehemken Sorry dude, this `new_nat_gateway` arg does have issues, this have been fixed in https://github.com/terraform-providers/terraform-provider-alicloud/pull/410
When you disable `new_nat_gateway`, it still create clusters with `new_nat_gateway` enabled.
Just like what this issue describes https://github.com/alibaba/terraform-provider/issues/707

When cluster is in failed state, current code doesn't handle this state very well. For this, I'll do a debug, try to catch this case.

Thank you very much!
