### ISSUE TITLE
Is oss domain supported?

### ISSUE THREAD

**Issue by xinyifly** [alibaba/terraform-provider#743]
Besides `alicloud_dns_record` , I need to bind a `Self-Hosted Domain Name` in follow console.
https://oss.console.aliyun.com/bucket/oss-cn-hangzhou/BUCKET-NAME/domain
As well as specify(paste content) https certificate there.

**Comment by coderall** [comment]
Hi @xinyifly  , please look this doc https://www.alibabacloud.com/help/doc-detail/31836.htm?spm=a2c63.l28256.b99.36.294e5139KIip8q

**Comment by clouda3** [comment]
Does terraform support domain on the bucket? I checked the ducument but I did not find the domain name could bind to the bucket.
