### ISSUE TITLE
Terraform creating alicloud instance doesn't support multi nic configuration.

### ISSUE THREAD

**Issue by DimiDimov** [alibaba/terraform-provider#746]
basically same as this ticket but for alicloud https://github.com/hashicorp/terraform/issues/13564

you can see on the terraform documentation that for GCE and other clouds making mulitiple NIC configurations is supported but it is not supported in alicloud

Usually in the template there is a line about  network_interface such as here: https://www.terraform.io/docs/providers/google/r/compute_instance.html

Alicloud documentation does not show that: https://www.terraform.io/docs/providers/alicloud/r/instance.html

**Comment by QqqRy** [comment]
@danawillow, I also encountered the same problem. I noticed that Alibaba Cloud supports the creation of eni. I don't know why terriform doesn't support it. Can this be optimized?

**Comment by danawillow** [comment]
Hey @QqqRy! I work on the Google provider, so I'm afraid I won't be much help here.

**Comment by xiaozhu36** [comment]
HI @DimiDimov What is multi NIC? Is it alibaba cloud ENI: https://www.alibabacloud.com/help/doc-detail/58504.htm? If so, now, we are woking on it and please be patient.

**Comment by DimiDimov** [comment]
Yup sorry I didn't realize that was a term internal to my company. Multi-NIC is ability to add multiple NIC's at the creation of the VM. Sounds like that's what you're already working on so that's great thanks!

**Comment by QqqRy** [comment]
@xiaozhu36 , I am very happy that you are doing this, and what you are doing is exactly what I need. I want to know when I can use this feature?

**Comment by xiaozhu36** [comment]
HI @DimiDimov @QqqRy The release 1.23.0 has supported network interface resources. Please check it.

**Comment by DimiDimov** [comment]
Thank you!
