### ISSUE TITLE
ECS module not recognizing region

### ISSUE THREAD

**Issue by bscott** [alibaba/terraform-provider#75]
Hello,

I'm using the alicloud-ecs-vpc module and it seems that even if I set my region, the module still points to "https://ecs-cn-hangzhou.aliyuncs.com"

```
 alicloud_security_group_rule.allow_all_udp: Error SecurityGroup rule: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:""}, HostId:"", Code:"AliyunGoClientFailure", Message:"Get https://ecs-cn-hangzhou.aliyuncs.com?AccessKeyId=
```

I omitted some of the error.

**Comment by usualstuff** [comment]
To me it's seems like an error in configuration, "https://ecs-cn-hangzhou.aliyuncs.com" - AFAIK it's just an address for API, it should be same for all regions.
Could you provide some code fore security group that you trying to configure?
I've done it for HK region and it works just fine.

**Comment by bscott** [comment]
Closing for now
