### ISSUE TITLE
SLB: invalid or unknown key: PersistenceTimeout

### ISSUE THREAD

**Issue by usualstuff** [alibaba/terraform-provider#76]
Hello.

I'm trying to configure SLB to use multiple listeners and for some I want persistense for connection.
I see that [API](https://intl.aliyun.com/help/doc-detail/27594.htm) supports ```PersistenceTimeout``` option and it defined in [resource_alicloud_slb.go](https://github.com/alibaba/terraform-provider/blob/59a1e7b55ce7a6f2a0b7099c4000ead65850ffaf/alicloud/resource_alicloud_slb.go) as well. But when I try to describe it like this, I've got ```invalid or unknown key: PersistenceTimeout``` error:
```
resource "alicloud_slb" test-slb" {
  name = "test-slb"
  internet_charge_type = "paybytraffic"
  internet = true

  listener = [
  {
    "instance_port" = "443"
    "lb_port" = "443"
    "lb_protocol" = "tcp"
    "bandwidth" = "100"
  }]

  listener = [
  {
    "instance_port" = "8100"
    "lb_port" = "8100"
    "lb_protocol" = "tcp"
    "bandwidth" = "100"
    "PersistenceTimeout" = "3600"
  }]

  depends_on = [ "alicloud_vpc.main"]
}
```

What I'm doing wrong? Maybe binary for linux needs an update?

Thanks,
Alex

**Comment by usualstuff** [comment]
I've done some checks: it's really looks like linux binary is out of date.
Could you please update it?
Or at lease fix compiling errors from master:
```
$ go get ./...# github.com/alibaba/terraform-provider/alicloud
alicloud/data_source_alicloud_images.go:234: image.OSType undefined (type ecs.ImageType has no field or method OSType)
alicloud/data_source_alicloud_images.go:236: image.Platform undefined (type ecs.ImageType has no field or method Platform)
alicloud/data_source_alicloud_images.go:240: image.IsSelfShared undefined (type ecs.ImageType has no field or method IsSelfShared)
alicloud/data_source_alicloud_images.go:242: image.IsCopied undefined (type ecs.ImageType has no field or method IsCopied)
alicloud/data_source_alicloud_images.go:243: image.IsSupportIoOptimized undefined (type ecs.ImageType has no field or method IsSupportIoOptimized)
alicloud/data_source_alicloud_images.go:246: image.Usage undefined (type ecs.ImageType has no field or method Usage)
alicloud/data_source_alicloud_instance_types.go:71: conn.DescribeInstanceTypesNew undefined (type *ecs.Client has no field or method DescribeInstanceTypesNew)
alicloud/data_source_alicloud_instance_types.go:123: args.InstanceTypeFamily undefined (type *ecs.DescribeInstanceTypesArgs has no field or method InstanceTypeFamily)
alicloud/resource_alicloud_security_group_rule.go:231: undefined: ecs.AuthorizeSecurityGroupEgressArgs
alicloud/service_alicloud_ecs.go:205: undefined: ecs.RevokeSecurityGroupArgs
alicloud/data_source_alicloud_instance_types.go:123: too many errors
```

Thanks,
Alex

**Comment by shuwei-yin** [comment]
@usualstuff slb listener following to try it please:
listener = [
    {
      "instance_port" = "2111"
      "lb_port" = "21"
      "lb_protocol" = "tcp"
      "bandwidth" = 1
    },{
      "instance_port" = "8000"
      "lb_port" = "80"
      "lb_protocol" = "http"
      "bandwidth" = 1
    },{
      "instance_port" = "1611"
      "lb_port" = "161"
      "lb_protocol" = "udp"
      "bandwidth" = 1
    }]

**Comment by shuwei-yin** [comment]
for those errors please upgrade your go sdk, the folder is denverdino/aliyungo, or you delete "vendor" folder then go get ./... try it again.

the linux binary address is "http://tf-linux.oss-cn-shanghai.aliyuncs.com/terraform-provider-alicloud.zip", did you download it?

**Comment by usualstuff** [comment]
I've updated binary for provider but problem still present: when I add ```PersistenceTimeout``` option for SLB, I get an error: ```invalid or unknown key: PersistenceTimeout```

Configuration looks like this:
```
resource "alicloud_slb" "production-slb" {
  name = "production-slb"
  internet_charge_type = "paybytraffic"
  internet = true

  listener = [
  {
    "instance_port" = "81"
    "lb_port" = "81"
    "lb_protocol" = "tcp"
    "bandwidth" = "100"
    "PersistenceTimeout" = "3600"
  }]

  depends_on = [ "alicloud_vpc.main"]
}
```

Thanks,
Alex

**Comment by wangyuelucky** [comment]
Hi @usualstuff 
I've updated the binary file http://tf-linux.oss-cn-shanghai.aliyuncs.com/terraform-provider-alicloud.zip
Hope it works,please try again.

BTW, the [lasted version](https://www.terraform.io/downloads.html) of terraform already include alicloud provider, Any suggestions are very grateful.

Thanks,
wangyuelucky

**Comment by shuwei-yin** [comment]
Hi @usualstuff 
I'm Sorry that the SLB listener PersistenceTimeout invalid.
Now It's fixed. please get the last version from https://github.com/alibaba/terraform-provider/releases (V1.0.3), and the version addition healthcheck functional.
The listener describe parameter please reference: https://github.com/alibaba/terraform-provider/tree/master/terraform/examples/alicloud-slb.

Thanks
