### ISSUE TITLE
Getting a wrong error message when using a wrong credentials

### ISSUE THREAD

**Issue by achachw** [alibaba/terraform-provider#761]
I am using the last alicloud provider version v1.20.0.
When entering a wrong (wrong, expired, ..) credentials i am getting this error message : 

* alicloud_vpc.test-vpc: Create vpc got an error :&errors.ClientError{errorCode:"**SDK.CanNotResolveEndpoint**", message:"**Can not resolve endpoint**(param = {\"Domain\":\"\",\"Product\":\"Vpc\",\"RegionId\":\"eu-central-1\",\"LocationProduct\":\"vpc\",\"LocationEndpointType\":\"openAPI\"}), please check the user guide\n ", originError:error(nil)}

**Comment by xiaozhu36** [comment]
HI @achachw Please check your access_key and secret key and then try again.

**Comment by terryzwt** [comment]
@xiaozhu36 I encounter the same problem. But  in this official examples, I don't find any variable for access_key and secret_key; and there is no document to describe how to set up them. So based on the examples, what is the best practice to set up the access_key & secret_key variables?

**Comment by xiaozhu36** [comment]
Hi @terryzwt Please refer to : https://www.terraform.io/docs/providers/alicloud/index.html

**Comment by terryzwt** [comment]
@xiaozhu36 thx. 
Before I check your reply, I have already solved the problem from the docs you provided. 
But I have spend some hours to find the solution. 
So I suggest you provide the same docs on this project; so the other people  will benefit from it and get time saved.

**Comment by xiaozhu36** [comment]
@terryzwt Thanks for your feedback. I will plan it.

**Comment by xiaozhu36** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-alicloud/pull/504
