### ISSUE TITLE
inner_access = false feature of alicloud_security_group doesn't work as expected  after terraform apply run at first time.

### ISSUE THREAD

**Issue by ala2208** [alibaba/terraform-provider#766]
Hi,

I created alicloud_security_group with property **inner_access = false** and alicloud_security_group_rule with some source_security_group_id.
In this case I expected both machines are not allowed to access each other on all ports in the same security group.
But after I run "terraform apply" at first time, I'm able to access one machine from another in the same security group.
When I run "terraform apply" again, terraform notifies that will perform the next actions:
       inner_access: "true" => "false"
After "terraform apply" ran on second time the inner access feature behaved as expected (machines are not allowed to access each other on all ports in the same security group).

**Comment by xiaozhu36** [comment]
HI @ala2208 This issue has been fixed and it will be released in the next version. Please be patient.

**Comment by nightmeng** [comment]
We have fixed it in master branch.

**Comment by xiaozhu36** [comment]
HI @ala2208 The release 1.23.0 has fixed it. Please check it.
