### ISSUE TITLE
Does alicloud_cdn_domain support https/cert config?

### ISSUE THREAD

**Issue by xinyifly** [alibaba/terraform-provider#769]
https://www.terraform.io/docs/providers/alicloud/r/cdn_domain.html

**Comment by kelly-apollo** [comment]
+1

**Comment by xiaozhu36** [comment]
HI @kelly-apollo This issue has been fixed by https://github.com/terraform-providers/terraform-provider-alicloud/pull/605 and it will be supported by the next release.

**Comment by xiaozhu36** [comment]
Fixed by 1.28.0.
