### ISSUE TITLE
bind network interface to ecs instance on boot

### ISSUE THREAD

**Issue by DimiDimov** [alibaba/terraform-provider#772]
So creating network interfaces is now possible with 1.23 as shown by https://github.com/alibaba/terraform-provider/issues/746

However, I don't see a way to bind these network interface to an instance at boot.
I'm referring to the documentation here:
https://www.terraform.io/docs/providers/alicloud/r/instance.html
Where a list of network interfaces to bind to the instance is not an optional argument. 

I saw this is possible on google cloud using terraform as per documentation here: https://www.terraform.io/docs/providers/google/r/compute_instance.html#network_interface

My goal is to launch a ecs_instance in a VPC with three different network interfaces each connected to their own vswitch in the same VPC

Let me know if you need any more information on this

**Comment by nightmeng** [comment]
@DimiDimov I think you can create network interfaces and attach the network interfaces to instance at boot with `alicloud_network_interface` and `alicloud_network_interface_attachment`:
https://www.terraform.io/docs/providers/alicloud/r/network_interface.html
https://www.terraform.io/docs/providers/alicloud/r/network_interface_attachment.html

**Comment by xiaozhu36** [comment]
Closed for no reply.
