### ISSUE TITLE
Not able to create MNS queue

### ISSUE THREAD

**Issue by ankurops** [alibaba/terraform-provider#774]
Hi, I am trying to create mns queue in alibaba using terraform. Geeting below error.

* alicloud_mns_queue.queue: Create queue got an error: &errors.errorCode{err:errors.Error{ID:"CB7B68F", Namespace:"MNS", Code:0x5, Message:"send request failed, dialing to the given TCP address timed out"}, stackTrace:"/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/dxh031/ali_mns/client.go:227        (*aliMNSClient).Send\n/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/dxh031/ali_mns/utils.go:12          send\n/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/dxh031/ali_mns/queue_manager.go:130 (*MNSQueueManager).CreateQueue\n/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/alicloud/resource_alicloud_mns_queue.go:83            resourceAlicloudMNSQueueCreate.func1\n/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/alicloud/connectivity/client.go:718                   (*AliyunClient).WithMnsQueueManager.func1", context:map[string]interface {}{}, errors:[]string(nil)}

**Comment by xiaozhu36** [comment]
HI @ankurops Can you show me your TF template?

**Comment by xiaozhu36** [comment]
Closed by no reply
