### ISSUE TITLE
example on terraform alicloud provider's page caused 'intranet' error

### ISSUE THREAD

**Issue by lonegunmanb** [alibaba/terraform-provider#779]
Hello guys, when I copied example you provided on [https://www.terraform.io/docs/providers/alicloud/r/security_group_rule.html](url) like this:
`resource "alicloud_security_group" "default" {
  name = "default"
}

resource "alicloud_security_group_rule" "allow_all_tcp" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "internet"
  policy            = "accept"
  port_range        = "1/65535"
  priority          = 1
  security_group_id = "${alicloud_security_group.default.id}"
  cidr_ip           = "0.0.0.0/0"
}`
I got an error:
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group_rule.go:129:
When security group in the vpc or authorizing permission for source/destination security group, the nic_type must be 'intranet'.

  on main.tf line 41, in resource "alicloud_security_group_rule" "allow_all_tcp":
  41: resource "alicloud_security_group_rule" "allow_all_tcp" {

Something wrong with example or document?

**Comment by zhangyoufu** [comment]
根据API文档，对于VPC网络，`NicType`必须指定为`intranet`。把Terraform样例中`nic_type`整行删除即可。

**Comment by lonegunmanb** [comment]
> 根据API文档，对于VPC网络，`NicType`必须指定为`intranet`。把Terraform样例中`nic_type`整行删除即可。

感谢您的指教
